/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import Entidades.Mesero;
import Entidades.Pedido;
import Entidades.Producto;
import Persistencia.MeseroData;
import Persistencia.PedidoData;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.table.DefaultTableModel;


public class ViewEstadisticas extends javax.swing.JInternalFrame {
    
    private String nombreMesero;
    public ViewEstadisticas(String nombreMesero) {
        this.nombreMesero= nombreMesero;
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        labelTotalFecha.setVisible(false);
        jTextArea.setVisible(false);
        jTextArea.setEditable(false);
        
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCalendar1 = new com.toedter.calendar.JCalendar();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        JlblIngresosTotales = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        JlblBuscarPedidosCobrados = new javax.swing.JLabel();
        jCalendar = new com.toedter.calendar.JCalendar();
        labelTotalFecha = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea = new javax.swing.JTextArea();

        setPreferredSize(new java.awt.Dimension(1024, 690));

        jPanel1.setBackground(new java.awt.Color(51, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setForeground(new java.awt.Color(102, 51, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 690));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(102, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(255, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 204, 153));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fast-food_737967.png"))); // NOI18N
        jLabel3.setText("Estadisticas");
        jLabel3.setIconTextGap(12);
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 217, 90));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 0, 0));
        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(941, 36, 43, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 1068, -1));

        JlblIngresosTotales.setBackground(new java.awt.Color(51, 153, 0));
        JlblIngresosTotales.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        JlblIngresosTotales.setForeground(new java.awt.Color(255, 255, 255));
        JlblIngresosTotales.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JlblIngresosTotales.setText("Ingresos totales de la fecha");
        JlblIngresosTotales.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        JlblIngresosTotales.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JlblIngresosTotales.setOpaque(true);
        JlblIngresosTotales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JlblIngresosTotalesMouseClicked(evt);
            }
        });
        jPanel1.add(JlblIngresosTotales, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 570, 240, 50));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Pedido", "ID Cliente", "ID Mesa", "Fecha", "ID Mesero", "Nombre Mesero"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 580, 380));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Resultados");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 580, 20));

        JlblBuscarPedidosCobrados.setBackground(new java.awt.Color(51, 153, 0));
        JlblBuscarPedidosCobrados.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        JlblBuscarPedidosCobrados.setForeground(new java.awt.Color(255, 255, 255));
        JlblBuscarPedidosCobrados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JlblBuscarPedidosCobrados.setText("Buscar pedidos Cobrados");
        JlblBuscarPedidosCobrados.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        JlblBuscarPedidosCobrados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JlblBuscarPedidosCobrados.setOpaque(true);
        JlblBuscarPedidosCobrados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JlblBuscarPedidosCobradosMouseClicked(evt);
            }
        });
        jPanel1.add(JlblBuscarPedidosCobrados, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 570, 230, 50));
        jPanel1.add(jCalendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 130, 340, 170));

        labelTotalFecha.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelTotalFecha.setForeground(new java.awt.Color(255, 204, 153));
        jPanel1.add(labelTotalFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 520, 380, 30));

        jTextArea.setColumns(20);
        jTextArea.setRows(5);
        jScrollPane2.setViewportView(jTextArea);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 320, 300, 130));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 27, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void JlblIngresosTotalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JlblIngresosTotalesMouseClicked
        limpiarFilas();
        double total=0;
        Date fecha = jCalendar.getDate();
        PedidoData pd=new PedidoData();
        List <Pedido>listaTotal = new ArrayList<>();
        listaTotal=pd.obtenerPedidosParaSumar(fecha);
       total= cargarTablaTotal(listaTotal);
        
       
        jTextArea.setText("Ingresos totales en la fecha \n " + fecha.toString()+ "\n Fueron  de  "+ total);
        jTextArea.setVisible(true);
    }//GEN-LAST:event_JlblIngresosTotalesMouseClicked

    private void JlblBuscarPedidosCobradosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JlblBuscarPedidosCobradosMouseClicked
       jTextArea.setVisible(false);
        limpiarFilas();
        Mesero mesero=null;
        Date fecha=jCalendar.getDate();
        PedidoData pd = new PedidoData();
        MeseroData md = new MeseroData();
       mesero= md.buscarMeseroPorNombre(nombreMesero);
       List <Pedido> listaPedidos= new ArrayList<>();
       listaPedidos= pd.obtenerPedidosPorFecha(fecha, mesero.getId());
      cargarTablaPedido(listaPedidos);
    }//GEN-LAST:event_JlblBuscarPedidosCobradosMouseClicked

  private void cargarTablaPedido(List<Pedido> pedidos) {
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setRowCount(0);

        for (Pedido p : pedidos) {
            modelo.addRow(new Object[]{
                p.getIdPedido(),
                p.getCliente().getId(),
                p.getMesa().getIdMesa(),
                p.getFecha().toString(),
                p.getMesero().getId(),
                p.getMesero().getNombre()
                
            });
        }
    }
  
   private double cargarTablaTotal(List<Pedido> pedidos) {
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setRowCount(0);
        double total=0;
        for (Pedido p : pedidos) {
           total=total+ p.getMontoTotal();
            modelo.addRow(new Object[]{
                p.getIdPedido(),
                p.getCliente().getId(),
                p.getMesa().getIdMesa(),
                p.getFecha().toString(),
                p.getMesero().getId(),
                p.getMesero().getNombre()
                
            });
        }
        
        return total;
    }
  
      
  
  private void limpiarFilas(){
    int contador=  jTable1.getRowCount();
    DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
      for (int i = contador-1; i >= 0; i--) {
         modelo.removeRow(i);
      }
  }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JlblBuscarPedidosCobrados;
    private javax.swing.JLabel JlblIngresosTotales;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JCalendar jCalendar;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea;
    private javax.swing.JLabel labelTotalFecha;
    // End of variables declaration//GEN-END:variables
}
