/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Image;
import java.beans.PropertyVetoException;
import javax.swing.ImageIcon;
import javax.swing.JInternalFrame;
import javax.swing.JPanel;
import AppPackage.AnimationClass;
import Entidades.Mesero;
import Persistencia.MeseroData;
import javax.swing.JOptionPane;
/**
 *
 * @author ariel
 */
public class ViewLogin extends javax.swing.JFrame {
        
    /**
     * Creates new form ViewPrincipal
     */
    public ViewLogin() {
        
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        JlbRegistrarse = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jtfUsuario = new javax.swing.JTextField();
        jpfContraseña = new javax.swing.JPasswordField();
        jbIngresar = new javax.swing.JButton();
        jPfondo = new FondoPanel();
        JTRegistroNombre = new javax.swing.JTextField();
        JlblNewCamarero = new javax.swing.JLabel();
        JlblRegistroNombre = new javax.swing.JLabel();
        JlblRegistroDni = new javax.swing.JLabel();
        JTRegistroDni = new javax.swing.JTextField();
        JbRegistro1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        botonprueba = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setResizable(false);

        escritorio.setBackground(new java.awt.Color(102, 51, 0));
        escritorio.setForeground(new java.awt.Color(102, 51, 0));

        jPanel1.setBackground(new java.awt.Color(51, 0, 0));
        jPanel1.setForeground(new java.awt.Color(102, 51, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(219, 198, 83));
        jLabel3.setText("RESTAURANTE");
        jLabel3.setToolTipText("");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, 330, 51));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/olla-calienteiCON.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 90, 70));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, 100));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 40, 580));

        JlbRegistrarse.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        JlbRegistrarse.setForeground(new java.awt.Color(219, 198, 83));
        JlbRegistrarse.setText("Registrarse en el sistema");
        JlbRegistrarse.setToolTipText("");
        JlbRegistrarse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JlbRegistrarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JlbRegistrarseMouseClicked(evt);
            }
        });
        jPanel1.add(JlbRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 590, 270, 40));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/camarero.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 90, 70));

        jLabel6.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(219, 198, 83));
        jLabel6.setText("Usuario:");
        jLabel6.setToolTipText("");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 90, 40));

        jSeparator2.setBackground(new java.awt.Color(219, 198, 83));
        jSeparator2.setForeground(new java.awt.Color(219, 198, 83));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 280, 20));

        jSeparator3.setBackground(new java.awt.Color(219, 198, 83));
        jSeparator3.setForeground(new java.awt.Color(219, 198, 83));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 280, 20));

        jtfUsuario.setBackground(new java.awt.Color(51, 0, 0));
        jtfUsuario.setForeground(new java.awt.Color(204, 204, 204));
        jtfUsuario.setBorder(null);
        jtfUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(jtfUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 324, 280, 40));

        jpfContraseña.setBackground(new java.awt.Color(51, 0, 0));
        jpfContraseña.setForeground(new java.awt.Color(204, 204, 204));
        jpfContraseña.setText("jPasswordField1");
        jpfContraseña.setBorder(null);
        jPanel1.add(jpfContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 432, 280, 30));

        jbIngresar.setBackground(new java.awt.Color(51, 0, 0));
        jbIngresar.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jbIngresar.setForeground(new java.awt.Color(219, 198, 83));
        jbIngresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Offline.png"))); // NOI18N
        jbIngresar.setText("  Ingresar");
        jbIngresar.setBorder(null);
        jbIngresar.setBorderPainted(false);
        jbIngresar.setContentAreaFilled(false);
        jbIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbIngresar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Online.png"))); // NOI18N
        jbIngresar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Online.png"))); // NOI18N
        jbIngresar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Online.png"))); // NOI18N
        jbIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbIngresarActionPerformed(evt);
            }
        });
        jPanel1.add(jbIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 210, 70));

        jPfondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPfondo.add(JTRegistroNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, -150, 370, 40));

        JlblNewCamarero.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        JlblNewCamarero.setForeground(new java.awt.Color(219, 198, 83));
        JlblNewCamarero.setText("Nuevo Camarero:");
        JlblNewCamarero.setToolTipText("");
        JlblNewCamarero.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPfondo.add(JlblNewCamarero, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, -150, 300, 60));

        JlblRegistroNombre.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        JlblRegistroNombre.setForeground(new java.awt.Color(219, 198, 83));
        JlblRegistroNombre.setText("Nombre:");
        JlblRegistroNombre.setToolTipText("");
        JlblRegistroNombre.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPfondo.add(JlblRegistroNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, -150, 300, 60));

        JlblRegistroDni.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        JlblRegistroDni.setForeground(new java.awt.Color(219, 198, 83));
        JlblRegistroDni.setText("DNI:");
        JlblRegistroDni.setToolTipText("");
        JlblRegistroDni.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPfondo.add(JlblRegistroDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, -150, 300, 60));
        jPfondo.add(JTRegistroDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, -150, 370, 40));

        JbRegistro1.setText("Registrarme!");
        JbRegistro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbRegistro1ActionPerformed(evt);
            }
        });
        jPfondo.add(JbRegistro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, -150, -1, -1));

        jPanel1.add(jPfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 910, 580));

        jLabel8.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(219, 198, 83));
        jLabel8.setText("Registro de camareros");
        jLabel8.setToolTipText("");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 300, 90));

        jLabel9.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(219, 198, 83));
        jLabel9.setText("Contraseña:");
        jLabel9.setToolTipText("");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 130, 40));

        botonprueba.setText("Prueba");
        botonprueba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonpruebaActionPerformed(evt);
            }
        });
        jPanel1.add(botonprueba, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 560, -1, -1));

        escritorio.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbIngresarActionPerformed
        String usuario = jtfUsuario.getText().trim();
        String password = new String(jpfContraseña.getPassword()).trim();

        // Instancia de MeseroData para verificar en la base de datos
        MeseroData meseroData = new MeseroData();

        // Llamamos a un método que valida si el nombre de usuario coincide con el nombre de mesero y el DNI como contraseña
        Mesero mesero = meseroData.buscarMeseroPorNombreYDni(usuario, password);

        if (mesero != null) {
            // Si los datos son correctos, abrir el menú principal
            ViewMenuPrincipal vmp = new ViewMenuPrincipal(mesero.getNombre());
            vmp.setVisible(true);
            vmp.setSize(1318,779);
            escritorio.add(vmp);
            vmp.moveToFront();
            JOptionPane.showMessageDialog(this, "Bienvenido " + usuario , "Ingreso al sistema", JOptionPane.INFORMATION_MESSAGE);
        } else {
            // Si los datos son incorrectos, muestra un mensaje de error
            JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbIngresarActionPerformed

    private void JlbRegistrarseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JlbRegistrarseMouseClicked
        JlbRegistrarse.setText("Registrarse en el sistema");
        Color amarillito = new Color(219, 198, 83);
        JlbRegistrarse.setForeground(amarillito);
        AnimationClass registro = new AnimationClass();
        registro.jLabelYUp(-150, 30, 10, 5,JlblNewCamarero );
        registro.jLabelYUp(-150, 200, 10, 5,JlblRegistroDni );
        registro.jLabelYUp(-150, 80, 10, 5,JlblRegistroNombre );
        registro.jButtonYUp(-150, 360, 10, 5, JbRegistro1);
        registro.jTextFieldYUp(-150, 250, 10, 5, JTRegistroDni);
        registro.jTextFieldYUp(-150, 130, 10, 5, JTRegistroNombre);
    }//GEN-LAST:event_JlbRegistrarseMouseClicked

    private void jtfUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfUsuarioActionPerformed

    private void JbRegistro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbRegistro1ActionPerformed
        AnimationClass registro = new AnimationClass();
        String nombre = JTRegistroNombre.getText().trim();
        String dni = JTRegistroDni.getText().trim();

        // Validación básica de campos vacíos
        if (!nombre.matches("[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+")) {
            JOptionPane.showMessageDialog(this, "El nombre solo puede contener letras", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (!dni.matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "El DNI solo puede contener números", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

    // Validación de que los campos no estén vacíos
    if (nombre.isEmpty() || dni.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, completa todos los campos", "Error", JOptionPane.WARNING_MESSAGE);
        return;
    }
        // Creación de la instancia de Mesero y registro en la base de datos
        Mesero mesero = new Mesero(0, nombre, dni); // '0' porque el ID lo autogenera la base de datos
        MeseroData meseroData = new MeseroData();

        boolean registrado = meseroData.crearMesero(mesero);

        if (registrado) {
            registro.jLabelYUp(30, -150, 10, 5,JlblNewCamarero );
            registro.jLabelYUp(200, -150, 10, 5,JlblRegistroDni );
            registro.jLabelYUp(80, -150, 10, 5,JlblRegistroNombre );
            registro.jButtonYUp(360, -150, 10, 5, JbRegistro1);
            registro.jTextFieldYUp(250, -150, 10, 5, JTRegistroDni);
            registro.jTextFieldYUp(130, -150, 10, 5, JTRegistroNombre);
            JOptionPane.showMessageDialog(this, "Mesero registrado con éxito", "Registro exitoso", JOptionPane.INFORMATION_MESSAGE);
            JTRegistroNombre.setText("");
            JTRegistroDni.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "Error al registrar el mesero", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_JbRegistro1ActionPerformed

    private void botonpruebaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonpruebaActionPerformed
            ViewMenuPrincipal vmp = new ViewMenuPrincipal("Jeremias");
            vmp.setVisible(true);
            vmp.setSize(1318,779);
            escritorio.add(vmp);
            vmp.moveToFront();
    }//GEN-LAST:event_botonpruebaActionPerformed

    
  
    private void agregarInternalFrame(JInternalFrame ifr) {
        escritorio.removeAll();
        escritorio.repaint();
        
        try {
            ifr.setMaximum(true);
        } catch (PropertyVetoException e) {
            e.printStackTrace();
        }
        
        ifr.setVisible(true);
        escritorio.add(ifr);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTRegistroDni;
    private javax.swing.JTextField JTRegistroNombre;
    private javax.swing.JButton JbRegistro1;
    private javax.swing.JLabel JlbRegistrarse;
    private javax.swing.JLabel JlblNewCamarero;
    private javax.swing.JLabel JlblRegistroDni;
    private javax.swing.JLabel JlblRegistroNombre;
    private javax.swing.JButton botonprueba;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPfondo;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton jbIngresar;
    private javax.swing.JPasswordField jpfContraseña;
    private javax.swing.JTextField jtfUsuario;
    // End of variables declaration//GEN-END:variables
class FondoPanel extends JPanel {
        private Image imagen;
        
        @Override
        public void paint(Graphics g){
            imagen = new ImageIcon(getClass().getResource("/img/un_restaurante[1].png")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(),this);
            
            setOpaque(false);
            super.paint(g);
        }
    }
}
