/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import Entidades.Producto;
import Persistencia.ProductoData;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class ViewProducto extends javax.swing.JInternalFrame {
    public ViewProducto() {
        initComponents();
        cargarProductosEnTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        JlblEliminar = new javax.swing.JLabel();
        JlblAgregar = new javax.swing.JLabel();
        JlblModificar = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jtfNombre = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jtfTipo = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jtfStock = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jtfPrecio = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();

        setPreferredSize(new java.awt.Dimension(1024, 690));

        jPanel1.setBackground(new java.awt.Color(51, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        jPanel1.setForeground(new java.awt.Color(102, 51, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 690));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(102, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(255, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 204, 153));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fast-food_737967.png"))); // NOI18N
        jLabel3.setText("Productos");
        jLabel3.setIconTextGap(12);
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 217, 90));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 0, 0));
        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(941, 36, 43, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 1068, -1));

        jTable2.setBackground(new java.awt.Color(102, 0, 0));
        jTable2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTable2.setForeground(new java.awt.Color(255, 204, 153));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Tipo", "Stock", "Precio"
            }
        ));
        jTable2.setToolTipText("");
        jTable2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable2.setRequestFocusEnabled(false);
        jTable2.setShowGrid(true);
        jTable2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTable2FocusLost(evt);
            }
        });
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 970, 335));

        JlblEliminar.setBackground(new java.awt.Color(255, 0, 0));
        JlblEliminar.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        JlblEliminar.setForeground(new java.awt.Color(255, 255, 255));
        JlblEliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JlblEliminar.setText("Eliminar");
        JlblEliminar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        JlblEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JlblEliminar.setOpaque(true);
        JlblEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JlblEliminarMouseClicked(evt);
            }
        });
        jPanel1.add(JlblEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 540, 100, 50));

        JlblAgregar.setBackground(new java.awt.Color(51, 153, 0));
        JlblAgregar.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        JlblAgregar.setForeground(new java.awt.Color(255, 255, 255));
        JlblAgregar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JlblAgregar.setText("Agregar");
        JlblAgregar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        JlblAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JlblAgregar.setOpaque(true);
        JlblAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JlblAgregarMouseClicked(evt);
            }
        });
        jPanel1.add(JlblAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 540, 100, 50));

        JlblModificar.setBackground(new java.awt.Color(0, 0, 255));
        JlblModificar.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        JlblModificar.setForeground(new java.awt.Color(255, 255, 255));
        JlblModificar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JlblModificar.setText("Modificar");
        JlblModificar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        JlblModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JlblModificar.setOpaque(true);
        JlblModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JlblModificarMouseClicked(evt);
            }
        });
        jPanel1.add(JlblModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 540, 100, 50));

        jPanel2.setForeground(new java.awt.Color(102, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtfNombre.setBackground(new java.awt.Color(242, 242, 242));
        jtfNombre.setForeground(new java.awt.Color(102, 0, 0));
        jtfNombre.setBorder(null);
        jPanel2.add(jtfNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 170, 20));

        jLabel7.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 0, 0));
        jLabel7.setText("Nombre");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        jLabel8.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 0, 0));
        jLabel8.setText("Stock");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, -1, 30));

        jLabel9.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 0, 0));
        jLabel9.setText("Tipo");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, 30));

        jLabel10.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 0, 0));
        jLabel10.setText("Precio");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, -1, 30));

        jSeparator1.setForeground(new java.awt.Color(102, 0, 0));
        jSeparator1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 170, 10));

        jSeparator2.setForeground(new java.awt.Color(102, 0, 0));
        jSeparator2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 170, 10));

        jtfTipo.setBackground(new java.awt.Color(242, 242, 242));
        jtfTipo.setForeground(new java.awt.Color(102, 0, 0));
        jtfTipo.setBorder(null);
        jPanel2.add(jtfTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 170, 20));

        jSeparator3.setForeground(new java.awt.Color(102, 0, 0));
        jSeparator3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 170, 10));

        jtfStock.setBackground(new java.awt.Color(242, 242, 242));
        jtfStock.setForeground(new java.awt.Color(102, 0, 0));
        jtfStock.setBorder(null);
        jPanel2.add(jtfStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 170, 20));

        jSeparator4.setForeground(new java.awt.Color(102, 0, 0));
        jSeparator4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, 170, 10));

        jtfPrecio.setBackground(new java.awt.Color(242, 242, 242));
        jtfPrecio.setForeground(new java.awt.Color(102, 0, 0));
        jtfPrecio.setBorder(null);
        jPanel2.add(jtfPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 40, 170, 20));

        jComboBox1.setBackground(new java.awt.Color(242, 242, 242));
        jComboBox1.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Productos disponibles", "Productos sin stock" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 20, 190, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 970, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTable2FocusLost

    }//GEN-LAST:event_jTable2FocusLost

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
       
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked

    }//GEN-LAST:event_jTable2MouseClicked

    private void JlblAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JlblAgregarMouseClicked
        String nombre = jtfNombre.getText();
        int cantidad = Integer.parseInt(jtfStock.getText());
        double precio = Double.parseDouble(jtfPrecio.getText());
        String tipo = jtfTipo.getText();

        Producto nuevoProducto = new Producto(0, nombre, cantidad, precio, tipo);  // El ID se ignora (0), ya que es autoincremental

        ProductoData productoData = new ProductoData();
        productoData.agregarProducto(nuevoProducto);
        actualizarTabla();
    }//GEN-LAST:event_JlblAgregarMouseClicked

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        ProductoData productoData = new ProductoData();
        List<Producto> productos;

        if (jComboBox1.getSelectedItem().equals("Productos sin stock")) {
            productos = productoData.listarProductosSinStock();
        } else {
            productos = productoData.listarProductos();
        }
        cargarTablaProductos(productos);

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void JlblModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JlblModificarMouseClicked
        int selectedRow = jTable2.getSelectedRow();

        if (selectedRow != -1) { 
            int idProducto = (int) jTable2.getValueAt(selectedRow, 0);

            String nombre = jtfNombre.getText();
            String tipo = jtfTipo.getText();
            String cantidadText = jtfStock.getText();
            String precioText = jtfPrecio.getText();

            if (nombre.isEmpty() && tipo.isEmpty() && cantidadText.isEmpty() && precioText.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Debe llenar al menos un campo para modificar el producto.", "Campos vacíos", JOptionPane.WARNING_MESSAGE);
                return;
            }

            try {
                // Construir el producto con los valores actuales de la tabla y reemplazar solo los ingresados
                Producto productoOriginal = new Producto(
                    idProducto,
                    (String) jTable2.getValueAt(selectedRow, 1),  // nombre original
                    (int) jTable2.getValueAt(selectedRow, 3),     // cantidad original
                    (double) jTable2.getValueAt(selectedRow, 4),  // precio original
                    (String) jTable2.getValueAt(selectedRow, 2)   // tipo original
                );

                // Modificar solo los campos que el usuario completó
                if (!nombre.isEmpty()) {
                    productoOriginal.setNombre(nombre);
                }
                if (!tipo.isEmpty()) {
                    productoOriginal.setTipo(tipo);
                }
                if (!cantidadText.isEmpty()) {
                    productoOriginal.setCantidad(Integer.parseInt(cantidadText));
                }
                if (!precioText.isEmpty()) {
                    productoOriginal.setPrecio(Double.parseDouble(precioText));
                }

                // Llamar al método de modificación en ProductoData con el producto modificado
                ProductoData productoData = new ProductoData();
                productoData.editarProducto(idProducto, productoOriginal);

                // Mensaje de confirmación y actualización de la tabla
                JOptionPane.showMessageDialog(this, "Producto modificado exitosamente.");
                actualizarTabla();  // Refresca la tabla después de modificar

            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Los campos de cantidad y precio deben contener valores numéricos válidos.", "Error de formato", JOptionPane.ERROR_MESSAGE);
            }

        } else {
            JOptionPane.showMessageDialog(this, "Seleccione un producto de la tabla para modificar.", "Sin selección", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_JlblModificarMouseClicked

    private void JlblEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JlblEliminarMouseClicked
       int selectedRow = jTable2.getSelectedRow();

        if (selectedRow != -1) { 
            int idProducto = (int) jTable2.getValueAt(selectedRow, 0);
            String nombreProducto = (String) jTable2.getValueAt(selectedRow, 1);

            ProductoData productoData = new ProductoData();
            productoData.eliminarProducto(idProducto);
            JOptionPane.showMessageDialog(this, "Producto \"" + nombreProducto + "\" eliminado satisfactoriamente.");
            actualizarTabla();

        } else {
            JOptionPane.showMessageDialog(this, "Seleccione un producto de la tabla para eliminar.", "Sin selección", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_JlblEliminarMouseClicked

    
    
    private void cargarTablaProductos(List<Producto> productos) {
        DefaultTableModel modelo = (DefaultTableModel) jTable2.getModel();
        modelo.setRowCount(0);

        for (Producto producto : productos) {
            modelo.addRow(new Object[]{
                producto.getIdProducto(),
                producto.getNombre(),
                producto.getTipo(),
                producto.getCantidad(),
                producto.getPrecio()
            });
        }
    }
    
    private void actualizarTabla() {
    if (jComboBox1.getSelectedItem().equals("Productos sin stock")) {
        cargarTablaProductos(new ProductoData().listarProductosSinStock());
    } else {
        cargarTablaProductos(new ProductoData().listarProductos());
    }
}
    private void cargarProductosEnTabla() {
        ProductoData productoData = new ProductoData();
        List<Producto> productos = productoData.listarProductos();
        cargarTablaProductos(productos); 
}
      
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JlblAgregar;
    private javax.swing.JLabel JlblEliminar;
    private javax.swing.JLabel JlblModificar;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jtfNombre;
    private javax.swing.JTextField jtfPrecio;
    private javax.swing.JTextField jtfStock;
    private javax.swing.JTextField jtfTipo;
    // End of variables declaration//GEN-END:variables
}
