/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import Entidades.Mesa;
import Persistencia.MesaData;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class ViewMenuPrincipal extends javax.swing.JInternalFrame {
    private String nombreMesero;
    private Mesa[] mesas = new Mesa[12]; // Máximo 12 mesas
    private JLabel[] mesaLabels = new JLabel[12]; // Máximo 12 JLabels
    private JLabel selectedLabel = null;
    private MesaData md;
    private List <Mesa> mesasList = new ArrayList<>();
    private static int mesasAgregadas;
    /**
     * Creates new form ViewMenuPrincipal
     */
    public ViewMenuPrincipal(String nombreMesero) {
        md= new MesaData();
      mesasList=md.listarMesas();
      mesasAgregadas=mesasList.size();
        initComponents();
        this.nombreMesero = nombreMesero;
        inicializarMesas();
         traerMesasDB();
        actualizarComboBoxMesas();
        jlblNombreLoggin.setText(nombreMesero);
        actualizarBotonesEstadoMesas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        cantidadMesasComboBox = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        JtCapacidadMesas = new javax.swing.JTextField();
        btnProductos1 = new javax.swing.JButton();
        JbAceptarMesa = new javax.swing.JButton();
        jDialog2 = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        JtModificarCapMesas = new javax.swing.JTextField();
        JlblMesaSeleccionada = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        JCEstadoDeMesa = new javax.swing.JComboBox<>();
        JbAceptarModificarMesa = new javax.swing.JButton();
        JbCancelarModificarMesa = new javax.swing.JButton();
        jDialog3 = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        JbCancelar = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        JbFinalizarPedido = new javax.swing.JButton();
        JbEliminar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNombreCliente = new javax.swing.JTextField();
        JbAgregar = new javax.swing.JButton();
        escritorio = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        JlblNumMesa = new javax.swing.JLabel();
        JlblMesa2 = new javax.swing.JLabel();
        JbDesloggear = new javax.swing.JButton();
        JbModificarMesa = new javax.swing.JButton();
        JbAEliminarMesa = new javax.swing.JButton();
        JlblMesa1 = new javax.swing.JLabel();
        JlblMesa3 = new javax.swing.JLabel();
        JlblMesa4 = new javax.swing.JLabel();
        JlblMesa5 = new javax.swing.JLabel();
        JlblMesa6 = new javax.swing.JLabel();
        JlblMesa7 = new javax.swing.JLabel();
        JlblMesa8 = new javax.swing.JLabel();
        JlblMesa9 = new javax.swing.JLabel();
        JlblMesa10 = new javax.swing.JLabel();
        JlblMesa11 = new javax.swing.JLabel();
        JlblMesa12 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        JlblCapMesa = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        JlblEstadoMesa = new javax.swing.JLabel();
        btnProductos = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnProductos2 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jlblNombreLoggin = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        JbAñadirMesa = new javax.swing.JButton();
        JbTomarPedidoMesa2 = new javax.swing.JButton();
        JbTomarPedidoMesa1 = new javax.swing.JButton();
        JbTomarPedidoMesa6 = new javax.swing.JButton();
        JbTomarPedidoMesa5 = new javax.swing.JButton();
        JbTomarPedidoMesa10 = new javax.swing.JButton();
        JbTomarPedidoMesa9 = new javax.swing.JButton();
        JbTomarPedidoMesa3 = new javax.swing.JButton();
        JbTomarPedidoMesa7 = new javax.swing.JButton();
        JbTomarPedidoMesa11 = new javax.swing.JButton();
        JbTomarPedidoMesa4 = new javax.swing.JButton();
        JbTomarPedidoMesa8 = new javax.swing.JButton();
        JbTomarPedidoMesa12 = new javax.swing.JButton();

        jPanel2.setBackground(new java.awt.Color(51, 0, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(580, 420));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Georgia", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(246, 23, 36));
        jLabel6.setText("(Maximo de 12)");
        jLabel6.setToolTipText("");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 130, 30));

        cantidadMesasComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 Mesa", "2  Mesas", "3 Mesas", "4 Mesas", "5 Mesas", "6 Mesas", "7 Mesas", "8 Mesas", "9 Mesas", "10 Mesas", "11 Mesas", "12 Mesas" }));
        cantidadMesasComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadMesasComboBoxActionPerformed(evt);
            }
        });
        jPanel2.add(cantidadMesasComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 130, -1));

        jLabel7.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(219, 198, 83));
        jLabel7.setText("Capacidad de las mesas:");
        jLabel7.setToolTipText("");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 270, 40));

        jLabel10.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(219, 198, 83));
        jLabel10.setText("Cantidad de mesas a añadir:");
        jLabel10.setToolTipText("");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 270, 40));
        jPanel2.add(JtCapacidadMesas, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 120, 50));

        btnProductos1.setBackground(new java.awt.Color(102, 0, 0));
        btnProductos1.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        btnProductos1.setForeground(new java.awt.Color(255, 204, 153));
        btnProductos1.setText("Cancelar");
        btnProductos1.setToolTipText("");
        btnProductos1.setBorderPainted(false);
        btnProductos1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnProductos1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnProductos1.setIconTextGap(12);
        btnProductos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductos1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnProductos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 130, 50));

        JbAceptarMesa.setBackground(new java.awt.Color(102, 0, 0));
        JbAceptarMesa.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        JbAceptarMesa.setForeground(new java.awt.Color(255, 204, 153));
        JbAceptarMesa.setText("Aceptar");
        JbAceptarMesa.setToolTipText("");
        JbAceptarMesa.setBorderPainted(false);
        JbAceptarMesa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JbAceptarMesa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JbAceptarMesa.setIconTextGap(12);
        JbAceptarMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbAceptarMesaActionPerformed(evt);
            }
        });
        jPanel2.add(JbAceptarMesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 120, 50));

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(51, 0, 0));
        jPanel3.setPreferredSize(new java.awt.Dimension(580, 420));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(219, 198, 83));
        jLabel11.setText("Mesa seleccionada:");
        jLabel11.setToolTipText("");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 190, 40));

        JtModificarCapMesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtModificarCapMesasActionPerformed(evt);
            }
        });
        jPanel3.add(JtModificarCapMesas, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 120, 50));

        JlblMesaSeleccionada.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        JlblMesaSeleccionada.setForeground(new java.awt.Color(219, 198, 83));
        JlblMesaSeleccionada.setText("1");
        JlblMesaSeleccionada.setToolTipText("");
        JlblMesaSeleccionada.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.add(JlblMesaSeleccionada, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 30, 40));

        jLabel13.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(219, 198, 83));
        jLabel13.setText("Estado:");
        jLabel13.setToolTipText("");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 80, 40));

        jLabel14.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(219, 198, 83));
        jLabel14.setText("Capacidad de la mesa:");
        jLabel14.setToolTipText("");
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 230, 40));

        JCEstadoDeMesa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Libre", "Ocupada", "Atendida", "Reservada" }));
        JCEstadoDeMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCEstadoDeMesaActionPerformed(evt);
            }
        });
        jPanel3.add(JCEstadoDeMesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 160, 40));

        JbAceptarModificarMesa.setBackground(new java.awt.Color(102, 0, 0));
        JbAceptarModificarMesa.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        JbAceptarModificarMesa.setForeground(new java.awt.Color(255, 204, 153));
        JbAceptarModificarMesa.setText("Aceptar");
        JbAceptarModificarMesa.setToolTipText("");
        JbAceptarModificarMesa.setBorderPainted(false);
        JbAceptarModificarMesa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JbAceptarModificarMesa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JbAceptarModificarMesa.setIconTextGap(12);
        JbAceptarModificarMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbAceptarModificarMesaActionPerformed(evt);
            }
        });
        jPanel3.add(JbAceptarModificarMesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 120, 50));

        JbCancelarModificarMesa.setBackground(new java.awt.Color(102, 0, 0));
        JbCancelarModificarMesa.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        JbCancelarModificarMesa.setForeground(new java.awt.Color(255, 204, 153));
        JbCancelarModificarMesa.setText("Cancelar");
        JbCancelarModificarMesa.setToolTipText("");
        JbCancelarModificarMesa.setBorderPainted(false);
        JbCancelarModificarMesa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JbCancelarModificarMesa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JbCancelarModificarMesa.setIconTextGap(12);
        JbCancelarModificarMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbCancelarModificarMesaActionPerformed(evt);
            }
        });
        jPanel3.add(JbCancelarModificarMesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 130, 50));

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jDialog3.setPreferredSize(new java.awt.Dimension(520, 498));

        jPanel4.setBackground(new java.awt.Color(51, 0, 0));
        jPanel4.setPreferredSize(new java.awt.Dimension(520, 498));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JbCancelar.setBackground(new java.awt.Color(102, 0, 0));
        JbCancelar.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        JbCancelar.setForeground(new java.awt.Color(255, 204, 153));
        JbCancelar.setText("Cancelar");
        JbCancelar.setToolTipText("");
        JbCancelar.setBorderPainted(false);
        JbCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JbCancelar.setIconTextGap(12);
        JbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbCancelarActionPerformed(evt);
            }
        });
        jPanel4.add(JbCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 470, 110, 40));

        jLabel20.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(219, 198, 83));
        jLabel20.setText("Producto:");
        jLabel20.setToolTipText("");
        jLabel20.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel21.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(219, 198, 83));
        jLabel21.setText("AGREGAR PEDIDO");
        jLabel21.setToolTipText("");
        jLabel21.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        jComboBox1.setBackground(new java.awt.Color(204, 204, 204));
        jComboBox1.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel4.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 150, 30));

        jTable1.setBackground(new java.awt.Color(176, 4, 47));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Producto", "Nombre", "Cantidad", "Monto"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 740, 290));

        jComboBox2.setBackground(new java.awt.Color(204, 204, 204));
        jComboBox2.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel4.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 150, 30));

        jLabel22.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(219, 198, 83));
        jLabel22.setText("Cantidad:");
        jLabel22.setToolTipText("");
        jLabel22.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        JbFinalizarPedido.setBackground(new java.awt.Color(102, 0, 0));
        JbFinalizarPedido.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        JbFinalizarPedido.setForeground(new java.awt.Color(255, 204, 153));
        JbFinalizarPedido.setText("Finalizar pedido");
        JbFinalizarPedido.setToolTipText("");
        JbFinalizarPedido.setBorderPainted(false);
        JbFinalizarPedido.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JbFinalizarPedido.setIconTextGap(12);
        JbFinalizarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbFinalizarPedidoActionPerformed(evt);
            }
        });
        jPanel4.add(JbFinalizarPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 470, 180, 40));

        JbEliminar.setBackground(new java.awt.Color(102, 0, 0));
        JbEliminar.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        JbEliminar.setForeground(new java.awt.Color(255, 204, 153));
        JbEliminar.setText("Eliminar");
        JbEliminar.setToolTipText("");
        JbEliminar.setBorderPainted(false);
        JbEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JbEliminar.setIconTextGap(12);
        JbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbEliminarActionPerformed(evt);
            }
        });
        jPanel4.add(JbEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 470, 110, 40));

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(219, 198, 83));
        jLabel1.setText("Nombre del cliente:");
        jLabel1.setToolTipText("");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, -1, -1));

        jTextFieldNombreCliente.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldNombreCliente.setForeground(new java.awt.Color(204, 204, 204));
        jPanel4.add(jTextFieldNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 260, 30));

        JbAgregar.setBackground(new java.awt.Color(102, 0, 0));
        JbAgregar.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        JbAgregar.setForeground(new java.awt.Color(255, 204, 153));
        JbAgregar.setText("Agregar");
        JbAgregar.setToolTipText("");
        JbAgregar.setBorderPainted(false);
        JbAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JbAgregar.setIconTextGap(12);
        JbAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbAgregarActionPerformed(evt);
            }
        });
        jPanel4.add(JbAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 470, 110, 40));

        javax.swing.GroupLayout jDialog3Layout = new javax.swing.GroupLayout(jDialog3.getContentPane());
        jDialog3.getContentPane().setLayout(jDialog3Layout);
        jDialog3Layout.setHorizontalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 789, Short.MAX_VALUE)
        );
        jDialog3Layout.setVerticalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
        );

        setPreferredSize(new java.awt.Dimension(1320, 680));

        escritorio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 0, 0));
        jPanel1.setForeground(new java.awt.Color(51, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 30, 770));

        jLabel8.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(219, 198, 83));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/camarero.png"))); // NOI18N
        jLabel8.setText(" ");
        jLabel8.setToolTipText("");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 70));

        JlblNumMesa.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        JlblNumMesa.setForeground(new java.awt.Color(219, 198, 83));
        JlblNumMesa.setText("No se ha seleccionado aun");
        JlblNumMesa.setToolTipText("");
        JlblNumMesa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(JlblNumMesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 10, 150, 40));

        JlblMesa2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Vacio.png"))); // NOI18N
        JlblMesa2.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Atendida.png"))); // NOI18N
        jPanel1.add(JlblMesa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 140, 200, 140));

        JbDesloggear.setBackground(new java.awt.Color(0, 51, 153));
        JbDesloggear.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        JbDesloggear.setForeground(new java.awt.Color(255, 153, 0));
        JbDesloggear.setText("Desloggear");
        JbDesloggear.setToolTipText("");
        JbDesloggear.setBorderPainted(false);
        JbDesloggear.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JbDesloggear.setIconTextGap(12);
        JbDesloggear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbDesloggearActionPerformed(evt);
            }
        });
        jPanel1.add(JbDesloggear, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, -1));

        JbModificarMesa.setBackground(new java.awt.Color(102, 0, 0));
        JbModificarMesa.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        JbModificarMesa.setForeground(new java.awt.Color(255, 204, 153));
        JbModificarMesa.setText("Modificar");
        JbModificarMesa.setToolTipText("");
        JbModificarMesa.setBorderPainted(false);
        JbModificarMesa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JbModificarMesa.setIconTextGap(12);
        JbModificarMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbModificarMesaActionPerformed(evt);
            }
        });
        jPanel1.add(JbModificarMesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 80, -1, -1));

        JbAEliminarMesa.setBackground(new java.awt.Color(102, 0, 0));
        JbAEliminarMesa.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        JbAEliminarMesa.setForeground(new java.awt.Color(255, 204, 153));
        JbAEliminarMesa.setText("Borrar");
        JbAEliminarMesa.setToolTipText("");
        JbAEliminarMesa.setBorderPainted(false);
        JbAEliminarMesa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JbAEliminarMesa.setIconTextGap(12);
        JbAEliminarMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbAEliminarMesaActionPerformed(evt);
            }
        });
        jPanel1.add(JbAEliminarMesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 80, -1, -1));

        JlblMesa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Vacio.png"))); // NOI18N
        JlblMesa1.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Atendida.png"))); // NOI18N
        jPanel1.add(JlblMesa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 200, 140));

        JlblMesa3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Vacio.png"))); // NOI18N
        JlblMesa3.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Atendida.png"))); // NOI18N
        jPanel1.add(JlblMesa3, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 140, -1, 140));

        JlblMesa4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Vacio.png"))); // NOI18N
        JlblMesa4.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Atendida.png"))); // NOI18N
        jPanel1.add(JlblMesa4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 140, 200, 140));

        JlblMesa5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Vacio.png"))); // NOI18N
        JlblMesa5.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Atendida.png"))); // NOI18N
        jPanel1.add(JlblMesa5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, 200, 140));

        JlblMesa6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Vacio.png"))); // NOI18N
        JlblMesa6.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Atendida.png"))); // NOI18N
        jPanel1.add(JlblMesa6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 310, 200, 140));

        JlblMesa7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Vacio.png"))); // NOI18N
        JlblMesa7.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Atendida.png"))); // NOI18N
        jPanel1.add(JlblMesa7, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 310, -1, 140));

        JlblMesa8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Vacio.png"))); // NOI18N
        JlblMesa8.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Atendida.png"))); // NOI18N
        jPanel1.add(JlblMesa8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 310, 200, 140));

        JlblMesa9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Vacio.png"))); // NOI18N
        JlblMesa9.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Atendida.png"))); // NOI18N
        jPanel1.add(JlblMesa9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 480, -1, 140));

        JlblMesa10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Vacio.png"))); // NOI18N
        JlblMesa10.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Atendida.png"))); // NOI18N
        jPanel1.add(JlblMesa10, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 480, 200, 140));

        JlblMesa11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Vacio.png"))); // NOI18N
        JlblMesa11.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Atendida.png"))); // NOI18N
        jPanel1.add(JlblMesa11, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 480, 200, 140));

        JlblMesa12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Vacio.png"))); // NOI18N
        JlblMesa12.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Atendida.png"))); // NOI18N
        jPanel1.add(JlblMesa12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 480, 200, 140));

        jLabel12.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(219, 198, 83));
        jLabel12.setText("Mesero en linea:");
        jLabel12.setToolTipText("");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 120, 50));

        jLabel15.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(219, 198, 83));
        jLabel15.setText("Mesa: ");
        jLabel15.setToolTipText("");
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 0, 80, 50));

        jLabel16.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(219, 198, 83));
        jLabel16.setText("Cap:");
        jLabel16.setToolTipText("");
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 30, 80, 50));

        JlblCapMesa.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        JlblCapMesa.setForeground(new java.awt.Color(219, 198, 83));
        JlblCapMesa.setText("No se ha seleccionado aun");
        JlblCapMesa.setToolTipText("");
        JlblCapMesa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(JlblCapMesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 40, 150, 40));

        jLabel18.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(219, 198, 83));
        jLabel18.setText("Estd:");
        jLabel18.setToolTipText("");
        jLabel18.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 70, 80, 50));

        JlblEstadoMesa.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        JlblEstadoMesa.setForeground(new java.awt.Color(219, 198, 83));
        JlblEstadoMesa.setText("No se ha seleccionado aun");
        JlblEstadoMesa.setToolTipText("");
        JlblEstadoMesa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(JlblEstadoMesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 80, 150, 40));

        btnProductos.setBackground(new java.awt.Color(102, 0, 0));
        btnProductos.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        btnProductos.setForeground(new java.awt.Color(255, 204, 153));
        btnProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fast-food_737967.png"))); // NOI18N
        btnProductos.setText("Productos");
        btnProductos.setToolTipText("");
        btnProductos.setBorderPainted(false);
        btnProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnProductos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnProductos.setIconTextGap(12);
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });
        jPanel1.add(btnProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 240, -1));

        jButton3.setBackground(new java.awt.Color(102, 0, 0));
        jButton3.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 204, 153));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pedido-en-linea.png"))); // NOI18N
        jButton3.setText("Pedidos");
        jButton3.setToolTipText("");
        jButton3.setBorderPainted(false);
        jButton3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton3.setIconTextGap(12);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 240, -1));

        btnProductos2.setBackground(new java.awt.Color(102, 0, 0));
        btnProductos2.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        btnProductos2.setForeground(new java.awt.Color(255, 204, 153));
        btnProductos2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/factura.png"))); // NOI18N
        btnProductos2.setText("Facturacion");
        btnProductos2.setToolTipText("");
        btnProductos2.setBorderPainted(false);
        btnProductos2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnProductos2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnProductos2.setIconTextGap(12);
        btnProductos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductos2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnProductos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        jLabel17.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(219, 198, 83));
        jLabel17.setText("Menu principal");
        jLabel17.setToolTipText("");
        jLabel17.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 300, 50));

        jlblNombreLoggin.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jlblNombreLoggin.setForeground(new java.awt.Color(219, 198, 83));
        jlblNombreLoggin.setText("Jeremias");
        jlblNombreLoggin.setToolTipText("");
        jlblNombreLoggin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jlblNombreLoggin, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 140, 50));

        jLabel19.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(219, 198, 83));
        jLabel19.setText("Mesas:");
        jLabel19.setToolTipText("");
        jLabel19.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 100, 50));

        JbAñadirMesa.setBackground(new java.awt.Color(102, 0, 0));
        JbAñadirMesa.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        JbAñadirMesa.setForeground(new java.awt.Color(255, 204, 153));
        JbAñadirMesa.setText("Añadir");
        JbAñadirMesa.setToolTipText("");
        JbAñadirMesa.setBorderPainted(false);
        JbAñadirMesa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JbAñadirMesa.setIconTextGap(12);
        JbAñadirMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbAñadirMesaActionPerformed(evt);
            }
        });
        jPanel1.add(JbAñadirMesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, -1, -1));

        JbTomarPedidoMesa2.setBackground(new java.awt.Color(102, 0, 0));
        JbTomarPedidoMesa2.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        JbTomarPedidoMesa2.setForeground(new java.awt.Color(255, 204, 153));
        JbTomarPedidoMesa2.setText("Tomar Pedido");
        JbTomarPedidoMesa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbTomarPedidoMesa2ActionPerformed(evt);
            }
        });
        jPanel1.add(JbTomarPedidoMesa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 280, -1, -1));

        JbTomarPedidoMesa1.setBackground(new java.awt.Color(102, 0, 0));
        JbTomarPedidoMesa1.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        JbTomarPedidoMesa1.setForeground(new java.awt.Color(255, 204, 153));
        JbTomarPedidoMesa1.setText("Tomar Pedido");
        JbTomarPedidoMesa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbTomarPedidoMesa1ActionPerformed(evt);
            }
        });
        jPanel1.add(JbTomarPedidoMesa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, -1, -1));

        JbTomarPedidoMesa6.setBackground(new java.awt.Color(102, 0, 0));
        JbTomarPedidoMesa6.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        JbTomarPedidoMesa6.setForeground(new java.awt.Color(255, 204, 153));
        JbTomarPedidoMesa6.setText("Tomar Pedido");
        JbTomarPedidoMesa6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbTomarPedidoMesa6ActionPerformed(evt);
            }
        });
        jPanel1.add(JbTomarPedidoMesa6, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 450, -1, -1));

        JbTomarPedidoMesa5.setBackground(new java.awt.Color(102, 0, 0));
        JbTomarPedidoMesa5.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        JbTomarPedidoMesa5.setForeground(new java.awt.Color(255, 204, 153));
        JbTomarPedidoMesa5.setText("Tomar Pedido");
        JbTomarPedidoMesa5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbTomarPedidoMesa5ActionPerformed(evt);
            }
        });
        jPanel1.add(JbTomarPedidoMesa5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 450, -1, -1));

        JbTomarPedidoMesa10.setBackground(new java.awt.Color(102, 0, 0));
        JbTomarPedidoMesa10.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        JbTomarPedidoMesa10.setForeground(new java.awt.Color(255, 204, 153));
        JbTomarPedidoMesa10.setText("Tomar Pedido");
        JbTomarPedidoMesa10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbTomarPedidoMesa10ActionPerformed(evt);
            }
        });
        jPanel1.add(JbTomarPedidoMesa10, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 620, -1, -1));

        JbTomarPedidoMesa9.setBackground(new java.awt.Color(102, 0, 0));
        JbTomarPedidoMesa9.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        JbTomarPedidoMesa9.setForeground(new java.awt.Color(255, 204, 153));
        JbTomarPedidoMesa9.setText("Tomar Pedido");
        JbTomarPedidoMesa9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbTomarPedidoMesa9ActionPerformed(evt);
            }
        });
        jPanel1.add(JbTomarPedidoMesa9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 620, -1, -1));

        JbTomarPedidoMesa3.setBackground(new java.awt.Color(102, 0, 0));
        JbTomarPedidoMesa3.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        JbTomarPedidoMesa3.setForeground(new java.awt.Color(255, 204, 153));
        JbTomarPedidoMesa3.setText("Tomar Pedido");
        JbTomarPedidoMesa3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbTomarPedidoMesa3ActionPerformed(evt);
            }
        });
        jPanel1.add(JbTomarPedidoMesa3, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 280, -1, -1));

        JbTomarPedidoMesa7.setBackground(new java.awt.Color(102, 0, 0));
        JbTomarPedidoMesa7.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        JbTomarPedidoMesa7.setForeground(new java.awt.Color(255, 204, 153));
        JbTomarPedidoMesa7.setText("Tomar Pedido");
        JbTomarPedidoMesa7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbTomarPedidoMesa7ActionPerformed(evt);
            }
        });
        jPanel1.add(JbTomarPedidoMesa7, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 450, -1, -1));

        JbTomarPedidoMesa11.setBackground(new java.awt.Color(102, 0, 0));
        JbTomarPedidoMesa11.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        JbTomarPedidoMesa11.setForeground(new java.awt.Color(255, 204, 153));
        JbTomarPedidoMesa11.setText("Tomar Pedido");
        JbTomarPedidoMesa11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbTomarPedidoMesa11ActionPerformed(evt);
            }
        });
        jPanel1.add(JbTomarPedidoMesa11, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 620, -1, -1));

        JbTomarPedidoMesa4.setBackground(new java.awt.Color(102, 0, 0));
        JbTomarPedidoMesa4.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        JbTomarPedidoMesa4.setForeground(new java.awt.Color(255, 204, 153));
        JbTomarPedidoMesa4.setText("Tomar Pedido");
        JbTomarPedidoMesa4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbTomarPedidoMesa4ActionPerformed(evt);
            }
        });
        jPanel1.add(JbTomarPedidoMesa4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 280, -1, -1));

        JbTomarPedidoMesa8.setBackground(new java.awt.Color(102, 0, 0));
        JbTomarPedidoMesa8.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        JbTomarPedidoMesa8.setForeground(new java.awt.Color(255, 204, 153));
        JbTomarPedidoMesa8.setText("Tomar Pedido");
        JbTomarPedidoMesa8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbTomarPedidoMesa8ActionPerformed(evt);
            }
        });
        jPanel1.add(JbTomarPedidoMesa8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 450, -1, -1));

        JbTomarPedidoMesa12.setBackground(new java.awt.Color(102, 0, 0));
        JbTomarPedidoMesa12.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        JbTomarPedidoMesa12.setForeground(new java.awt.Color(255, 204, 153));
        JbTomarPedidoMesa12.setText("Tomar Pedido");
        JbTomarPedidoMesa12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbTomarPedidoMesa12ActionPerformed(evt);
            }
        });
        jPanel1.add(JbTomarPedidoMesa12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 620, -1, -1));

        escritorio.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 1308, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JbDesloggearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbDesloggearActionPerformed
        int opcion = JOptionPane.showConfirmDialog(
        null, 
        "¿Seguro desea salir?", 
        "Salir del sistema", 
        JOptionPane.YES_NO_OPTION,
        JOptionPane.QUESTION_MESSAGE
        );
    
        if (opcion == JOptionPane.YES_OPTION) {
            dispose();
        }
    }//GEN-LAST:event_JbDesloggearActionPerformed

    private void JbModificarMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbModificarMesaActionPerformed
        if (selectedLabel != null && selectedLabel.getClientProperty("mesa") != null) {
            
        jDialog2.pack();
        jDialog2.setLocationRelativeTo(this);
        jDialog2.setVisible(true);

        Mesa mesa = (Mesa) selectedLabel.getClientProperty("mesa");
        int numeroMesa = mesa.getIdMesa();

        JlblMesaSeleccionada.setText("" + numeroMesa);
    } else {
        JOptionPane.showMessageDialog(null, "No se ha seleccionado ninguna mesa.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_JbModificarMesaActionPerformed

    private void JbAEliminarMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbAEliminarMesaActionPerformed
          
            
        
        if (selectedLabel == null) {
            JOptionPane.showMessageDialog(this, "No hay ninguna mesa seleccionada.");
            return;
        }

        Mesa mesaSeleccionada = (Mesa) selectedLabel.getClientProperty("mesa");

        if (mesaSeleccionada != null) {
            md.borrarMesa(mesaSeleccionada.getIdMesa());
            System.out.println("entro al if y deberia haber eliminado la mesa");
            mesaSeleccionada.setEstado(null);
            URL imageURL = getClass().getResource("/img/Vacio.png");
            ImageIcon icono = new ImageIcon(imageURL);
            selectedLabel.setIcon(icono); 
            selectedLabel.putClientProperty("mesa", null);
            selectedLabel = null;
        } else {
            JOptionPane.showMessageDialog(this, "La mesa seleccionada no tiene datos.");
        }
        mesasList=md.listarMesas();
      mesasAgregadas=mesasList.size();
        
         actualizarComboBoxMesas();
        
    }//GEN-LAST:event_JbAEliminarMesaActionPerformed

    private void btnProductos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductos1ActionPerformed
        jDialog1.dispose();
    }//GEN-LAST:event_btnProductos1ActionPerformed

    private void JbAceptarMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbAceptarMesaActionPerformed
       
        
        String capacidadTexto = JtCapacidadMesas.getText().trim();
    
    if (capacidadTexto.isEmpty()) {
        JOptionPane.showMessageDialog(
            this, 
            "Por favor, ingrese la capacidad de las mesas", 
            "Error", 
            JOptionPane.ERROR_MESSAGE
        );
        return;
    }
    
    // Intentar convertir la capacidad a número
    int capacidad;
    try {
        capacidad = Integer.parseInt(capacidadTexto);
        
        // Verificar que la capacidad sea un número positivo
        if (capacidad <= 0) {
            JOptionPane.showMessageDialog(
                this, 
                "La capacidad debe ser un número mayor a 0", 
                "Error", 
                JOptionPane.ERROR_MESSAGE
            );
            return;
        }
        
        // Si la conversión es exitosa, continuar con el resto del código
        int mesasAAgregar = cantidadMesasComboBox.getSelectedIndex() + 1;
        int mesasagregadasindice = 0;
        
        for (int i = 0; i < mesaLabels.length; i++) {
            JLabel mesaLabel = mesaLabels[i];
            if (mesaLabel.getClientProperty("mesa") != null) {
                mesasagregadasindice++;
            }
            System.out.println(mesasagregadasindice);
        }
        mesasagregadasindice = mesasagregadasindice + mesasAAgregar;
        
        //test consola
        System.out.println(mesasAAgregar);
        System.out.println(mesasAgregadas);
        System.out.println("hasta donde deberia llegar es hasta " + mesasagregadasindice);
         
        URL imageURL = getClass().getResource("/img/Libre.png");
        
        int indice = 0;    
            
        for (int i = 0; i < mesaLabels.length && mesasAAgregar > 0; i++) {
            System.out.println("entro al for");
            JLabel mesaLabel = mesaLabels[i];
            ImageIcon icono = new ImageIcon(imageURL);
            
            if (mesaLabel.getClientProperty("mesa") == null && indice < mesasagregadasindice) {
                try {
                    System.out.println("entrando al try");
                    Mesa nuevaMesa = new Mesa(i + 1, capacidad, "libre");
                    md.crearMesa(nuevaMesa);
                    mesaLabel.setIcon(icono);
                    mesaLabel.putClientProperty("mesa", nuevaMesa);
                    mesaLabel.setCursor(new Cursor(Cursor.HAND_CURSOR));
                } catch(Exception e) {
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(this, "Error al agregar la mesa");
                }
                    
                mesaLabel.addMouseListener(new MouseAdapter() {
                    @Override
                    public void mouseEntered(MouseEvent e) {
                        mesaLabel.setCursor(new Cursor(Cursor.HAND_CURSOR));
                    }
                    @Override
                    public void mouseClicked(MouseEvent e) {
                        if (selectedLabel != null) {
                            selectedLabel.setBorder(null);
                        }
                        mesaLabel.setBorder(BorderFactory.createLineBorder(Color.GREEN, 2));
                        selectedLabel = mesaLabel;
                        modificarLabelMesaSeleccionada();
                    }
                });
            }
            indice++;
        }
           
        System.out.println("salio del for");
        mesasList = md.listarMesas();
        mesasAgregadas = mesasList.size();
        
        actualizarComboBoxMesas();
        jDialog1.dispose();
        
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(
            this, 
            "Por favor, ingrese un número válido para la capacidad", 
            "Error", 
            JOptionPane.ERROR_MESSAGE
        );
    }
    }//GEN-LAST:event_JbAceptarMesaActionPerformed

    private void cantidadMesasComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadMesasComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadMesasComboBoxActionPerformed

    private void JCEstadoDeMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCEstadoDeMesaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCEstadoDeMesaActionPerformed

    private void JbAceptarModificarMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbAceptarModificarMesaActionPerformed
        // Obtener el estado seleccionado del JComboBox
        String estadoSeleccionado = (String) JCEstadoDeMesa.getSelectedItem(); // JCEstadoDeMesa es tu JComboBox

        // Obtener la nueva capacidad de la mesa desde el JTextField
        String capacidadTexto = JtModificarCapMesas.getText(); // JtModificarCapMesas es tu JTextField para capacidad
   
        // Verificar que la capacidad sea un número válido
        int nuevaCapacidad = 0;
        try {
            nuevaCapacidad = Integer.parseInt(capacidadTexto);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, ingresa una capacidad válida.");
            return;
        }

        actualizarImagenMesa(selectedLabel, estadoSeleccionado);

        Mesa mesaSeleccionada = (Mesa) selectedLabel.getClientProperty("mesa");
        if (mesaSeleccionada != null) {
            mesaSeleccionada.setCapacidad(nuevaCapacidad);
            mesaSeleccionada.setEstado(estadoSeleccionado); 
            md.modificarMesa(mesaSeleccionada);
        }
        
        actualizarBotonesEstadoMesas();
        jDialog2.dispose();

        JOptionPane.showMessageDialog(this, "La mesa se modificó con éxito.");
    }//GEN-LAST:event_JbAceptarModificarMesaActionPerformed

    private void JbCancelarModificarMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbCancelarModificarMesaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JbCancelarModificarMesaActionPerformed

    private void JtModificarCapMesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtModificarCapMesasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtModificarCapMesasActionPerformed

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed

        ViewProducto vp = new ViewProducto();  
        vp.setSize(1000, 650);       
        escritorio.setLayout(null);
        escritorio.add(vp);  
        vp.setVisible(true);  
        vp.moveToFront();     

    }//GEN-LAST:event_btnProductosActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
          
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnProductos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductos2ActionPerformed
        
    }//GEN-LAST:event_btnProductos2ActionPerformed

    private void JbAñadirMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbAñadirMesaActionPerformed
        mesasList=md.listarMesas();
        mesasAgregadas=mesasList.size();
        jDialog1.pack();
        jDialog1.setLocationRelativeTo(this);
        jDialog1.setVisible(true);
        actualizarComboBoxMesas();
    }//GEN-LAST:event_JbAñadirMesaActionPerformed

    private void JbTomarPedidoMesa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbTomarPedidoMesa1ActionPerformed
        jDialog3.pack();
        jDialog3.setLocationRelativeTo(this);
        jDialog3.setVisible(true);
    }//GEN-LAST:event_JbTomarPedidoMesa1ActionPerformed

    private void JbTomarPedidoMesa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbTomarPedidoMesa2ActionPerformed
        jDialog3.pack();
        jDialog3.setLocationRelativeTo(this);
        jDialog3.setVisible(true);
    }//GEN-LAST:event_JbTomarPedidoMesa2ActionPerformed

    private void JbTomarPedidoMesa5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbTomarPedidoMesa5ActionPerformed
        jDialog3.pack();
        jDialog3.setLocationRelativeTo(this);
        jDialog3.setVisible(true);
    }//GEN-LAST:event_JbTomarPedidoMesa5ActionPerformed

    private void JbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JbCancelarActionPerformed

    private void JbFinalizarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbFinalizarPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JbFinalizarPedidoActionPerformed

    private void JbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JbEliminarActionPerformed

    private void JbTomarPedidoMesa3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbTomarPedidoMesa3ActionPerformed
        jDialog3.pack();
        jDialog3.setLocationRelativeTo(this);
        jDialog3.setVisible(true);
    }//GEN-LAST:event_JbTomarPedidoMesa3ActionPerformed

    private void JbTomarPedidoMesa4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbTomarPedidoMesa4ActionPerformed
        jDialog3.pack();
        jDialog3.setLocationRelativeTo(this);
        jDialog3.setVisible(true);
    }//GEN-LAST:event_JbTomarPedidoMesa4ActionPerformed

    private void JbTomarPedidoMesa6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbTomarPedidoMesa6ActionPerformed
        jDialog3.pack();
        jDialog3.setLocationRelativeTo(this);
        jDialog3.setVisible(true);
    }//GEN-LAST:event_JbTomarPedidoMesa6ActionPerformed

    private void JbTomarPedidoMesa7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbTomarPedidoMesa7ActionPerformed
        jDialog3.pack();
        jDialog3.setLocationRelativeTo(this);
        jDialog3.setVisible(true);
    }//GEN-LAST:event_JbTomarPedidoMesa7ActionPerformed

    private void JbTomarPedidoMesa8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbTomarPedidoMesa8ActionPerformed
        jDialog3.pack();
        jDialog3.setLocationRelativeTo(this);
        jDialog3.setVisible(true);
    }//GEN-LAST:event_JbTomarPedidoMesa8ActionPerformed

    private void JbTomarPedidoMesa9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbTomarPedidoMesa9ActionPerformed
        jDialog3.pack();
        jDialog3.setLocationRelativeTo(this);
        jDialog3.setVisible(true);
    }//GEN-LAST:event_JbTomarPedidoMesa9ActionPerformed

    private void JbTomarPedidoMesa10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbTomarPedidoMesa10ActionPerformed
        jDialog3.pack();
        jDialog3.setLocationRelativeTo(this);
        jDialog3.setVisible(true);
    }//GEN-LAST:event_JbTomarPedidoMesa10ActionPerformed

    private void JbTomarPedidoMesa11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbTomarPedidoMesa11ActionPerformed
        jDialog3.pack();
        jDialog3.setLocationRelativeTo(this);
        jDialog3.setVisible(true);
    }//GEN-LAST:event_JbTomarPedidoMesa11ActionPerformed

    private void JbTomarPedidoMesa12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbTomarPedidoMesa12ActionPerformed
        jDialog3.pack();
        jDialog3.setLocationRelativeTo(this);
        jDialog3.setVisible(true);
    }//GEN-LAST:event_JbTomarPedidoMesa12ActionPerformed

    private void JbAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JbAgregarActionPerformed

    private void modificarLabelMesaSeleccionada(){
        Mesa mesaSeleccionada = (Mesa) selectedLabel.getClientProperty("mesa");

        if (mesaSeleccionada != null) {
            int numeroMesa = mesaSeleccionada.getIdMesa();
            int capacidad = mesaSeleccionada.getCapacidad(); 
            String estado = mesaSeleccionada.getEstado();    

            
            JlblNumMesa.setText("Número de Mesa: " + numeroMesa);
            JlblCapMesa.setText("Capacidad: " + capacidad);        
            JlblEstadoMesa.setText("Estado: " + estado);
            }else {
                JlblNumMesa.setText("No se ha seleccionado aun");
                JlblCapMesa.setText("No se ha seleccionado aun");        
                JlblEstadoMesa.setText("No se ha seleccionado aun");
            }
      }  
    private void inicializarMesas() {
       mesaLabels[0] = JlblMesa1;
       mesaLabels[1] = JlblMesa2;
       mesaLabels[2] = JlblMesa3;
       mesaLabels[3] = JlblMesa4;
       mesaLabels[4] = JlblMesa5;
       mesaLabels[5] = JlblMesa6;
       mesaLabels[6] = JlblMesa7;
       mesaLabels[7] = JlblMesa8;
       mesaLabels[8] = JlblMesa9;
       mesaLabels[9] = JlblMesa10;
       mesaLabels[10] = JlblMesa11;
       mesaLabels[11] = JlblMesa12;
    }
    
    private void traerMesasDB(){
            int i = 0;
        for (Mesa m : mesasList) {
            URL imageURL = getClass().getResource("/img/" + m.getEstado().toLowerCase() + ".png");
            ImageIcon icono = new ImageIcon(imageURL);
            JLabel mesaLabel = mesaLabels[i];
            mesaLabel.setIcon(icono);
            mesaLabel.putClientProperty("mesa", m);
            mesaLabel.setCursor(new Cursor(Cursor.HAND_CURSOR));
            i++;
            
            // Aquí se maneja el evento de hacer clic en las mesas
            mesaLabel.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseEntered(MouseEvent e) {
                    mesaLabel.setCursor(new Cursor(Cursor.HAND_CURSOR));
                }

                @Override
                public void mouseClicked(MouseEvent e) {
                    if (selectedLabel != null) {
                        selectedLabel.setBorder(null);
                    }

                    mesaLabel.setBorder(BorderFactory.createLineBorder(Color.GREEN, 2));

                    selectedLabel = mesaLabel;
                    modificarLabelMesaSeleccionada();
                }
            });
        }
    }
    //da el numero de mesas que aun se pueden agregar
    private void actualizarComboBoxMesas() {
        
        int maxMesas = 12;

        cantidadMesasComboBox.removeAllItems();

        for (int i = 1; i <= maxMesas - mesasAgregadas; i++) {
            cantidadMesasComboBox.addItem(i + " Mesas");
        }
    }

//    private int contarMesas() {
//        int contador = 0;
//        for (JLabel mesaLabel : mesaLabels) {
//            if (mesaLabel.getClientProperty("mesa") != null) {
//                contador++;
//            }
//        }
//        return contador;
//    }
    
    private void actualizarImagenMesa(JLabel mesaLabel, String estado) {
        URL imageURL;
        ImageIcon icono;

        switch (estado.toLowerCase()) {
            case "libre":
                imageURL = getClass().getResource("/img/libre.png");
                break;
            case "ocupada":
                imageURL = getClass().getResource("/img/ocupada.png");
                break;
            case "atendida":
                imageURL = getClass().getResource("/img/atendida.png");
                break;
            case "reservada":
                imageURL = getClass().getResource("/img/reservada.png");
                break;
            default:
                System.out.println("Estado no reconocido: " + estado);
                return;
        }

        if (imageURL == null) {
            System.out.println("Error: La imagen para el estado " + estado + " no se encontró.");
            return;
        }

        icono = new ImageIcon(imageURL);
        mesaLabel.setIcon(icono);
    }
    
    private void ocultarBotonMesa(int mesaIndex) {
        switch (mesaIndex) {
            case 0: JbTomarPedidoMesa1.setVisible(false); break;
            case 1: JbTomarPedidoMesa2.setVisible(false); break;
            case 2: JbTomarPedidoMesa3.setVisible(false); break;
            case 3: JbTomarPedidoMesa4.setVisible(false); break;
            case 4: JbTomarPedidoMesa5.setVisible(false); break;
            case 5: JbTomarPedidoMesa6.setVisible(false); break;
            case 6: JbTomarPedidoMesa7.setVisible(false); break;
            case 7: JbTomarPedidoMesa8.setVisible(false); break;
            case 8: JbTomarPedidoMesa9.setVisible(false); break;
            case 9: JbTomarPedidoMesa10.setVisible(false); break;
            case 10: JbTomarPedidoMesa11.setVisible(false); break;
            case 11: JbTomarPedidoMesa12.setVisible(false); break;
        }
    }

// Método para mostrar el botón de la mesa correspondiente
    private void mostrarBotonMesa(int mesaIndex) {
            switch (mesaIndex) {
            case 0: JbTomarPedidoMesa1.setVisible(true); break;
            case 1: JbTomarPedidoMesa2.setVisible(true); break;
            case 2: JbTomarPedidoMesa3.setVisible(true); break;
            case 3: JbTomarPedidoMesa4.setVisible(true); break;
            case 4: JbTomarPedidoMesa5.setVisible(true); break;
            case 5: JbTomarPedidoMesa6.setVisible(true); break;
            case 6: JbTomarPedidoMesa7.setVisible(true); break;
            case 7: JbTomarPedidoMesa8.setVisible(true); break;
            case 8: JbTomarPedidoMesa9.setVisible(true); break;
            case 9: JbTomarPedidoMesa10.setVisible(true); break;
            case 10: JbTomarPedidoMesa11.setVisible(true); break;
            case 11: JbTomarPedidoMesa12.setVisible(true); break;
        }
    }
        private Mesa obtenerMesa(int index) {
            JLabel mesaLabel = mesaLabels[index];  // Obtener el JLabel correspondiente al índice
            return (Mesa) mesaLabel.getClientProperty("mesa");  // Obtener la mesa asociada al JLabel
        }
    
       // Aquí, recorres todas las mesas y verificas su estado.
        private void actualizarBotonesEstadoMesas() {
            for (int i = 0; i < 12; i++) {
            Mesa mesa = obtenerMesa(i);  // Obtener la mesa correspondiente al índice
            if (mesa != null && "Ocupada".equals(mesa.getEstado())) {
                // Si la mesa está ocupada, mostrar el botón correspondiente
                mostrarBotonMesa(i);
            } else {
                // Si la mesa no está ocupada, ocultamos el botón
                ocultarBotonMesa(i);
            }
        }
        }
        
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JCEstadoDeMesa;
    private javax.swing.JButton JbAEliminarMesa;
    private javax.swing.JButton JbAceptarMesa;
    private javax.swing.JButton JbAceptarModificarMesa;
    private javax.swing.JButton JbAgregar;
    private javax.swing.JButton JbAñadirMesa;
    private javax.swing.JButton JbCancelar;
    private javax.swing.JButton JbCancelarModificarMesa;
    private javax.swing.JButton JbDesloggear;
    private javax.swing.JButton JbEliminar;
    private javax.swing.JButton JbFinalizarPedido;
    private javax.swing.JButton JbModificarMesa;
    private javax.swing.JButton JbTomarPedidoMesa1;
    private javax.swing.JButton JbTomarPedidoMesa10;
    private javax.swing.JButton JbTomarPedidoMesa11;
    private javax.swing.JButton JbTomarPedidoMesa12;
    private javax.swing.JButton JbTomarPedidoMesa2;
    private javax.swing.JButton JbTomarPedidoMesa3;
    private javax.swing.JButton JbTomarPedidoMesa4;
    private javax.swing.JButton JbTomarPedidoMesa5;
    private javax.swing.JButton JbTomarPedidoMesa6;
    private javax.swing.JButton JbTomarPedidoMesa7;
    private javax.swing.JButton JbTomarPedidoMesa8;
    private javax.swing.JButton JbTomarPedidoMesa9;
    private javax.swing.JLabel JlblCapMesa;
    private javax.swing.JLabel JlblEstadoMesa;
    private javax.swing.JLabel JlblMesa1;
    private javax.swing.JLabel JlblMesa10;
    private javax.swing.JLabel JlblMesa11;
    private javax.swing.JLabel JlblMesa12;
    private javax.swing.JLabel JlblMesa2;
    private javax.swing.JLabel JlblMesa3;
    private javax.swing.JLabel JlblMesa4;
    private javax.swing.JLabel JlblMesa5;
    private javax.swing.JLabel JlblMesa6;
    private javax.swing.JLabel JlblMesa7;
    private javax.swing.JLabel JlblMesa8;
    private javax.swing.JLabel JlblMesa9;
    private javax.swing.JLabel JlblMesaSeleccionada;
    private javax.swing.JLabel JlblNumMesa;
    private javax.swing.JTextField JtCapacidadMesas;
    private javax.swing.JTextField JtModificarCapMesas;
    private javax.swing.JButton btnProductos;
    private javax.swing.JButton btnProductos1;
    private javax.swing.JButton btnProductos2;
    private javax.swing.JComboBox<String> cantidadMesasComboBox;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JDialog jDialog3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldNombreCliente;
    private javax.swing.JLabel jlblNombreLoggin;
    // End of variables declaration//GEN-END:variables
}
