/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import Entidades.Conexion;
import Entidades.Pedido;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.time.LocalDateTime;
import java.util.ArrayList;
import javax.swing.JOptionPane;
/**
 *
 * @author USUARIO
 */
public class ViewPedido extends javax.swing.JInternalFrame {

    /**
     * Creates new form ViewPedido
     */
    public ViewPedido() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        pagado = new javax.swing.JButton();
        jButtonModificar = new javax.swing.JButton();
        jButtonEntregar = new javax.swing.JButton();
        jButtonAnulado = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtpedidos = new javax.swing.JTable();
        jButtonTicket = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(51, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(238, 238, 93));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pedido-en-linea.png"))); // NOI18N
        jLabel1.setText("PEDIDOS");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, -1, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 0, 0));
        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(773, 9, 43, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 15, 825, -1));

        pagado.setBackground(new java.awt.Color(102, 0, 0));
        pagado.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        pagado.setForeground(new java.awt.Color(255, 204, 153));
        pagado.setText("Pagado");
        pagado.setIconTextGap(12);
        pagado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagadojBtnBuscar(evt);
            }
        });
        jPanel1.add(pagado, new org.netbeans.lib.awtextra.AbsoluteConstraints(635, 434, 137, 40));

        jButtonModificar.setBackground(new java.awt.Color(102, 0, 0));
        jButtonModificar.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jButtonModificar.setForeground(new java.awt.Color(255, 204, 153));
        jButtonModificar.setText("Modificar");
        jButtonModificar.setIconTextGap(12);
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarjBtnBuscar(evt);
            }
        });
        jPanel1.add(jButtonModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(635, 273, -1, 40));

        jButtonEntregar.setBackground(new java.awt.Color(102, 0, 0));
        jButtonEntregar.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jButtonEntregar.setForeground(new java.awt.Color(255, 204, 153));
        jButtonEntregar.setText("Entregar");
        jButtonEntregar.setIconTextGap(12);
        jButtonEntregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEntregarjBtnBuscar(evt);
            }
        });
        jPanel1.add(jButtonEntregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(635, 492, 137, 40));

        jButtonAnulado.setBackground(new java.awt.Color(102, 0, 0));
        jButtonAnulado.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jButtonAnulado.setForeground(new java.awt.Color(255, 204, 153));
        jButtonAnulado.setText("Anulado");
        jButtonAnulado.setIconTextGap(12);
        jButtonAnulado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnuladojBtnBuscar(evt);
            }
        });
        jPanel1.add(jButtonAnulado, new org.netbeans.lib.awtextra.AbsoluteConstraints(635, 377, 137, 40));

        jtpedidos.setBackground(new java.awt.Color(102, 0, 0));
        jtpedidos.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jtpedidos.setForeground(new java.awt.Color(255, 255, 255));
        jtpedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtpedidos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 115, 556, 417));

        jButtonTicket.setBackground(new java.awt.Color(102, 0, 0));
        jButtonTicket.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jButtonTicket.setForeground(new java.awt.Color(255, 204, 153));
        jButtonTicket.setText("Ticket");
        jButtonTicket.setIconTextGap(12);
        jButtonTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTicketjBtnBuscar(evt);
            }
        });
        jPanel1.add(jButtonTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(635, 325, 137, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void pagadojBtnBuscar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagadojBtnBuscar
        // TODO add your handling code here:
    }//GEN-LAST:event_pagadojBtnBuscar

    private void jButtonModificarjBtnBuscar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarjBtnBuscar
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonModificarjBtnBuscar

    private void jButtonEntregarjBtnBuscar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEntregarjBtnBuscar
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEntregarjBtnBuscar

    private void jButtonAnuladojBtnBuscar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnuladojBtnBuscar
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAnuladojBtnBuscar

    private void jButtonTicketjBtnBuscar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTicketjBtnBuscar
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonTicketjBtnBuscar

    //metodos para agregar el pedido a tabla
    public void agregarPedidoATabla(int idPedido, int idCliente, int idMesa, int idMesero, double montoTotal, String fechaPedido, String estado, String pagado) {
    DefaultTableModel modelo = (DefaultTableModel) jtpedidos.getModel();
    Object[] fila = {idPedido, idCliente, idMesa, idMesero, montoTotal, fechaPedido, estado, pagado};
    modelo.addRow(fila);
}
    
    

   
    
    private void mostrarPedidosEnTabla(List<Pedido> pedidos) {
    DefaultTableModel modelo = (DefaultTableModel) jtpedidos.getModel();
    modelo.setRowCount(0); // Limpia la tabla antes de agregar datos

    // Define las columnas que quieres mostrar en la tabla
    String[] columnas = {"ID Pedido", "Cliente", "Mesa", "Mesero", "Monto Total", "Fecha", "Estado", "Pagado"};
    modelo.setColumnIdentifiers(columnas);

    // Itera sobre la lista de pedidos y agrega una fila por cada pedido
    for (Pedido pedido : pedidos) {
        Object[] fila = {
            pedido.getIdPedido(),
            pedido.getCliente().getNombre(), // Asumiendo que tienes un método getNombre() en Cliente
            pedido.getMesa().getIdMesa(), // Asumiendo que tienes un método getNumero() en Mesa
            pedido.getMesero().getNombre(), // Asumiendo que tienes un método getNombre() en Mesero
            pedido.getMontoTotal(),
            pedido.getFecha(),
            pedido.isEntregado() ? "Entregado" : "No entregado",
            pedido.isPagado() ? "Pagado" : "No Pagado"
        };
        modelo.addRow(fila);
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAnulado;
    private javax.swing.JButton jButtonEntregar;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JButton jButtonTicket;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtpedidos;
    private javax.swing.JButton pagado;
    // End of variables declaration//GEN-END:variables
}
