/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import Entidades.Mesa;
import Persistencia.MesaData;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class ViewMenuPrincipal extends javax.swing.JInternalFrame {
    
    private Mesa[] mesas = new Mesa[12]; // Máximo 12 mesas
    private JLabel[] mesaLabels = new JLabel[12]; // Máximo 12 JLabels
    private JLabel selectedLabel = null;
    private MesaData md;
    private List <Mesa> mesasList = new ArrayList<>();
    private static int mesasAgregadas;
    /**
     * Creates new form ViewMenuPrincipal
     */
    public ViewMenuPrincipal() {
        md= new MesaData();
      mesasList=md.listarMesas();
      mesasAgregadas=mesasList.size();
        initComponents();
        inicializarMesas();
         traerMesasDB();
        actualizarComboBoxMesas();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        cantidadMesasComboBox = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        JtCapacidadMesas = new javax.swing.JTextField();
        btnProductos1 = new javax.swing.JButton();
        JbAceptarMesa = new javax.swing.JButton();
        jDialog2 = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        JtModificarCapMesas = new javax.swing.JTextField();
        JlblMesaSeleccionada = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        JCEstadoDeMesa = new javax.swing.JComboBox<>();
        JbAceptarModificarMesa = new javax.swing.JButton();
        JbCancelarModificarMesa = new javax.swing.JButton();
        escritorio = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        JlblNumMesa = new javax.swing.JLabel();
        JlblMesa2 = new javax.swing.JLabel();
        JbAñadirMesa = new javax.swing.JButton();
        JbModificarMesa = new javax.swing.JButton();
        JbAEliminarMesa = new javax.swing.JButton();
        JlblMesa1 = new javax.swing.JLabel();
        JlblMesa3 = new javax.swing.JLabel();
        JlblMesa4 = new javax.swing.JLabel();
        JlblMesa5 = new javax.swing.JLabel();
        JlblMesa6 = new javax.swing.JLabel();
        JlblMesa7 = new javax.swing.JLabel();
        JlblMesa8 = new javax.swing.JLabel();
        JlblMesa9 = new javax.swing.JLabel();
        JlblMesa10 = new javax.swing.JLabel();
        JlblMesa11 = new javax.swing.JLabel();
        JlblMesa12 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        JlblCapMesa = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        JlblEstadoMesa = new javax.swing.JLabel();
        btnProductos = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnProductos2 = new javax.swing.JButton();

        jPanel2.setBackground(new java.awt.Color(51, 0, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(580, 420));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Georgia", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(246, 23, 36));
        jLabel6.setText("(Maximo de 12)");
        jLabel6.setToolTipText("");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 130, 30));

        cantidadMesasComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 Mesa", "2  Mesas", "3 Mesas", "4 Mesas", "5 Mesas", "6 Mesas", "7 Mesas", "8 Mesas", "9 Mesas", "10 Mesas", "11 Mesas", "12 Mesas" }));
        cantidadMesasComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadMesasComboBoxActionPerformed(evt);
            }
        });
        jPanel2.add(cantidadMesasComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 130, -1));

        jLabel7.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(219, 198, 83));
        jLabel7.setText("Capacidad de las mesas:");
        jLabel7.setToolTipText("");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 270, 40));

        jLabel10.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(219, 198, 83));
        jLabel10.setText("Cantidad de mesas a añadir:");
        jLabel10.setToolTipText("");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 270, 40));
        jPanel2.add(JtCapacidadMesas, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 120, 50));

        btnProductos1.setBackground(new java.awt.Color(102, 0, 0));
        btnProductos1.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        btnProductos1.setForeground(new java.awt.Color(255, 204, 153));
        btnProductos1.setText("Cancelar");
        btnProductos1.setToolTipText("");
        btnProductos1.setBorderPainted(false);
        btnProductos1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnProductos1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnProductos1.setIconTextGap(12);
        btnProductos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductos1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnProductos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 130, 50));

        JbAceptarMesa.setBackground(new java.awt.Color(102, 0, 0));
        JbAceptarMesa.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        JbAceptarMesa.setForeground(new java.awt.Color(255, 204, 153));
        JbAceptarMesa.setText("Aceptar");
        JbAceptarMesa.setToolTipText("");
        JbAceptarMesa.setBorderPainted(false);
        JbAceptarMesa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JbAceptarMesa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JbAceptarMesa.setIconTextGap(12);
        JbAceptarMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbAceptarMesaActionPerformed(evt);
            }
        });
        jPanel2.add(JbAceptarMesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 120, 50));

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(51, 0, 0));
        jPanel3.setPreferredSize(new java.awt.Dimension(580, 420));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(219, 198, 83));
        jLabel11.setText("Mesa seleccionada:");
        jLabel11.setToolTipText("");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 190, 40));

        JtModificarCapMesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtModificarCapMesasActionPerformed(evt);
            }
        });
        jPanel3.add(JtModificarCapMesas, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 120, 50));

        JlblMesaSeleccionada.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        JlblMesaSeleccionada.setForeground(new java.awt.Color(219, 198, 83));
        JlblMesaSeleccionada.setText("1");
        JlblMesaSeleccionada.setToolTipText("");
        JlblMesaSeleccionada.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.add(JlblMesaSeleccionada, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 30, 40));

        jLabel13.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(219, 198, 83));
        jLabel13.setText("Estado:");
        jLabel13.setToolTipText("");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 80, 40));

        jLabel14.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(219, 198, 83));
        jLabel14.setText("Capacidad de la mesa:");
        jLabel14.setToolTipText("");
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 230, 40));

        JCEstadoDeMesa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Libre", "Ocupada", "Atendida", "Reservada" }));
        JCEstadoDeMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCEstadoDeMesaActionPerformed(evt);
            }
        });
        jPanel3.add(JCEstadoDeMesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 160, 40));

        JbAceptarModificarMesa.setBackground(new java.awt.Color(102, 0, 0));
        JbAceptarModificarMesa.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        JbAceptarModificarMesa.setForeground(new java.awt.Color(255, 204, 153));
        JbAceptarModificarMesa.setText("Aceptar");
        JbAceptarModificarMesa.setToolTipText("");
        JbAceptarModificarMesa.setBorderPainted(false);
        JbAceptarModificarMesa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JbAceptarModificarMesa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JbAceptarModificarMesa.setIconTextGap(12);
        JbAceptarModificarMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbAceptarModificarMesaActionPerformed(evt);
            }
        });
        jPanel3.add(JbAceptarModificarMesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 120, 50));

        JbCancelarModificarMesa.setBackground(new java.awt.Color(102, 0, 0));
        JbCancelarModificarMesa.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        JbCancelarModificarMesa.setForeground(new java.awt.Color(255, 204, 153));
        JbCancelarModificarMesa.setText("Cancelar");
        JbCancelarModificarMesa.setToolTipText("");
        JbCancelarModificarMesa.setBorderPainted(false);
        JbCancelarModificarMesa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JbCancelarModificarMesa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JbCancelarModificarMesa.setIconTextGap(12);
        JbCancelarModificarMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbCancelarModificarMesaActionPerformed(evt);
            }
        });
        jPanel3.add(JbCancelarModificarMesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 130, 50));

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setPreferredSize(new java.awt.Dimension(1320, 680));

        escritorio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 0, 0));
        jPanel1.setForeground(new java.awt.Color(51, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 30, 770));

        jLabel8.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(219, 198, 83));
        jLabel8.setText("Mesas:");
        jLabel8.setToolTipText("");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 100, 50));

        JlblNumMesa.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        JlblNumMesa.setForeground(new java.awt.Color(219, 198, 83));
        JlblNumMesa.setText("No se ha seleccionado aun");
        JlblNumMesa.setToolTipText("");
        JlblNumMesa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(JlblNumMesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 10, 150, 40));

        JlblMesa2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Vacio.png"))); // NOI18N
        JlblMesa2.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Atendida.png"))); // NOI18N
        jPanel1.add(JlblMesa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 140, 200, 150));

        JbAñadirMesa.setBackground(new java.awt.Color(102, 0, 0));
        JbAñadirMesa.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        JbAñadirMesa.setForeground(new java.awt.Color(255, 204, 153));
        JbAñadirMesa.setText("Añadir");
        JbAñadirMesa.setToolTipText("");
        JbAñadirMesa.setBorderPainted(false);
        JbAñadirMesa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JbAñadirMesa.setIconTextGap(12);
        JbAñadirMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbAñadirMesaActionPerformed(evt);
            }
        });
        jPanel1.add(JbAñadirMesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, -1, -1));

        JbModificarMesa.setBackground(new java.awt.Color(102, 0, 0));
        JbModificarMesa.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        JbModificarMesa.setForeground(new java.awt.Color(255, 204, 153));
        JbModificarMesa.setText("Modificar");
        JbModificarMesa.setToolTipText("");
        JbModificarMesa.setBorderPainted(false);
        JbModificarMesa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JbModificarMesa.setIconTextGap(12);
        JbModificarMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbModificarMesaActionPerformed(evt);
            }
        });
        jPanel1.add(JbModificarMesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 80, -1, -1));

        JbAEliminarMesa.setBackground(new java.awt.Color(102, 0, 0));
        JbAEliminarMesa.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        JbAEliminarMesa.setForeground(new java.awt.Color(255, 204, 153));
        JbAEliminarMesa.setText("Borrar");
        JbAEliminarMesa.setToolTipText("");
        JbAEliminarMesa.setBorderPainted(false);
        JbAEliminarMesa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JbAEliminarMesa.setIconTextGap(12);
        JbAEliminarMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbAEliminarMesaActionPerformed(evt);
            }
        });
        jPanel1.add(JbAEliminarMesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 80, -1, -1));

        JlblMesa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Vacio.png"))); // NOI18N
        JlblMesa1.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Atendida.png"))); // NOI18N
        jPanel1.add(JlblMesa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 200, 150));

        JlblMesa3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Vacio.png"))); // NOI18N
        JlblMesa3.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Atendida.png"))); // NOI18N
        jPanel1.add(JlblMesa3, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 140, -1, 150));

        JlblMesa4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Vacio.png"))); // NOI18N
        JlblMesa4.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Atendida.png"))); // NOI18N
        jPanel1.add(JlblMesa4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 140, 200, 150));

        JlblMesa5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Vacio.png"))); // NOI18N
        JlblMesa5.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Atendida.png"))); // NOI18N
        jPanel1.add(JlblMesa5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, 200, 150));

        JlblMesa6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Vacio.png"))); // NOI18N
        JlblMesa6.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Atendida.png"))); // NOI18N
        jPanel1.add(JlblMesa6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 310, 200, 150));

        JlblMesa7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Vacio.png"))); // NOI18N
        JlblMesa7.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Atendida.png"))); // NOI18N
        jPanel1.add(JlblMesa7, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 310, -1, 150));

        JlblMesa8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Vacio.png"))); // NOI18N
        JlblMesa8.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Atendida.png"))); // NOI18N
        jPanel1.add(JlblMesa8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 300, 200, 150));

        JlblMesa9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Vacio.png"))); // NOI18N
        JlblMesa9.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Atendida.png"))); // NOI18N
        jPanel1.add(JlblMesa9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 480, -1, 150));

        JlblMesa10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Vacio.png"))); // NOI18N
        JlblMesa10.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Atendida.png"))); // NOI18N
        jPanel1.add(JlblMesa10, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 480, 200, 150));

        JlblMesa11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Vacio.png"))); // NOI18N
        JlblMesa11.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Atendida.png"))); // NOI18N
        jPanel1.add(JlblMesa11, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 480, 200, 150));

        JlblMesa12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Vacio.png"))); // NOI18N
        JlblMesa12.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Atendida.png"))); // NOI18N
        jPanel1.add(JlblMesa12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 480, 200, 150));

        jLabel12.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(219, 198, 83));
        jLabel12.setText("Menu principal");
        jLabel12.setToolTipText("");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 300, 50));

        jLabel15.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(219, 198, 83));
        jLabel15.setText("Mesa: ");
        jLabel15.setToolTipText("");
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 0, 80, 50));

        jLabel16.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(219, 198, 83));
        jLabel16.setText("Cap:");
        jLabel16.setToolTipText("");
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 30, 80, 50));

        JlblCapMesa.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        JlblCapMesa.setForeground(new java.awt.Color(219, 198, 83));
        JlblCapMesa.setText("No se ha seleccionado aun");
        JlblCapMesa.setToolTipText("");
        JlblCapMesa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(JlblCapMesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 40, 150, 40));

        jLabel18.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(219, 198, 83));
        jLabel18.setText("Estd:");
        jLabel18.setToolTipText("");
        jLabel18.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 70, 80, 50));

        JlblEstadoMesa.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        JlblEstadoMesa.setForeground(new java.awt.Color(219, 198, 83));
        JlblEstadoMesa.setText("No se ha seleccionado aun");
        JlblEstadoMesa.setToolTipText("");
        JlblEstadoMesa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(JlblEstadoMesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 80, 150, 40));

        btnProductos.setBackground(new java.awt.Color(102, 0, 0));
        btnProductos.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        btnProductos.setForeground(new java.awt.Color(255, 204, 153));
        btnProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fast-food_737967.png"))); // NOI18N
        btnProductos.setText("Productos");
        btnProductos.setToolTipText("");
        btnProductos.setBorderPainted(false);
        btnProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnProductos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnProductos.setIconTextGap(12);
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });
        jPanel1.add(btnProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 240, -1));

        jButton3.setBackground(new java.awt.Color(102, 0, 0));
        jButton3.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 204, 153));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/atencion-al-cliente.png"))); // NOI18N
        jButton3.setText("Clientes");
        jButton3.setToolTipText("");
        jButton3.setBorderPainted(false);
        jButton3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton3.setIconTextGap(12);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 240, -1));

        btnProductos2.setBackground(new java.awt.Color(102, 0, 0));
        btnProductos2.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        btnProductos2.setForeground(new java.awt.Color(255, 204, 153));
        btnProductos2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/factura.png"))); // NOI18N
        btnProductos2.setText("Facturacion");
        btnProductos2.setToolTipText("");
        btnProductos2.setBorderPainted(false);
        btnProductos2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnProductos2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnProductos2.setIconTextGap(12);
        btnProductos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductos2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnProductos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        escritorio.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 1308, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JbAñadirMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbAñadirMesaActionPerformed
       
        mesasList=md.listarMesas();
      mesasAgregadas=mesasList.size();
        
        jDialog1.pack();
        jDialog1.setLocationRelativeTo(this);
        jDialog1.setVisible(true);
        actualizarComboBoxMesas();
    }//GEN-LAST:event_JbAñadirMesaActionPerformed

    private void JbModificarMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbModificarMesaActionPerformed
        if (selectedLabel != null && selectedLabel.getClientProperty("mesa") != null) {
            
        jDialog2.pack();
        jDialog2.setLocationRelativeTo(this);
        jDialog2.setVisible(true);

        Mesa mesa = (Mesa) selectedLabel.getClientProperty("mesa");
        int numeroMesa = mesa.getIdMesa();

        JlblMesaSeleccionada.setText("" + numeroMesa);
    } else {
        JOptionPane.showMessageDialog(null, "No se ha seleccionado ninguna mesa.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_JbModificarMesaActionPerformed

    private void JbAEliminarMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbAEliminarMesaActionPerformed
          
            
        
        if (selectedLabel == null) {
            JOptionPane.showMessageDialog(this, "No hay ninguna mesa seleccionada.");
            return;
        }

        Mesa mesaSeleccionada = (Mesa) selectedLabel.getClientProperty("mesa");

        if (mesaSeleccionada != null) {
            md.borrarMesa(mesaSeleccionada.getIdMesa());
            System.out.println("entro al if y deberia haber eliminado la mesa");
            mesaSeleccionada.setEstado(null);
            URL imageURL = getClass().getResource("/img/Vacio.png");
            ImageIcon icono = new ImageIcon(imageURL);
            selectedLabel.setIcon(icono); 
            selectedLabel.putClientProperty("mesa", null);
            selectedLabel = null;
        } else {
            JOptionPane.showMessageDialog(this, "La mesa seleccionada no tiene datos.");
        }
        mesasList=md.listarMesas();
      mesasAgregadas=mesasList.size();
        
         actualizarComboBoxMesas();
        
    }//GEN-LAST:event_JbAEliminarMesaActionPerformed

    private void btnProductos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductos1ActionPerformed
        jDialog1.dispose();
    }//GEN-LAST:event_btnProductos1ActionPerformed

    private void JbAceptarMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbAceptarMesaActionPerformed
       
        
        int mesasAAgregar = cantidadMesasComboBox.getSelectedIndex() + 1;
        int capacidad = Integer.parseInt(JtCapacidadMesas.getText());
        int mesasagregadasindice=0;
        
        for (int i = 0; i < mesaLabels.length; i++) {
            JLabel mesaLabel = mesaLabels[i];
                if (mesaLabel.getClientProperty("mesa") !=null) {
                    mesasagregadasindice++;
                }
                System.out.println(mesasagregadasindice);
        }
        mesasagregadasindice = mesasagregadasindice+mesasAAgregar ;
        //test consola
         System.out.println(mesasAAgregar);
         System.out.println(mesasAgregadas);
         System.out.println("hasta donde deberia llegar es hasta "+  mesasagregadasindice);
         
        URL imageURL = getClass().getResource("/img/Libre.png");
        
            
            
        int indice=0;    
            
        for (int i = 0; i < mesaLabels.length && mesasAAgregar > 0; i++) {
            
            System.out.println("entro al for");
            JLabel mesaLabel = mesaLabels[i];
            ImageIcon icono = new ImageIcon(imageURL);
            
            
                
            
            if (mesaLabel.getClientProperty("mesa") == null && indice <mesasagregadasindice) {
                try{
                    System.out.println("entrando al try");
                Mesa nuevaMesa = new Mesa(i + 1, capacidad, "libre");
                md.crearMesa(nuevaMesa);
                mesaLabel.setIcon(icono);
                mesaLabel.putClientProperty("mesa", nuevaMesa);
                mesaLabel.setCursor(new Cursor(Cursor.HAND_CURSOR));
                }catch(Exception e){
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(this, "Error al agregar la mesa");
                }
                    
            mesaLabel.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseEntered(MouseEvent e) {
                    // Cambiar el cursor cuando se pasa sobre el JLabel
                    mesaLabel.setCursor(new Cursor(Cursor.HAND_CURSOR));
                }

                @Override
                public void mouseClicked(MouseEvent e) {
                    if (selectedLabel != null) {
                        selectedLabel.setBorder(null);
                    }

                    mesaLabel.setBorder(BorderFactory.createLineBorder(Color.GREEN, 2));

                    selectedLabel = mesaLabel;
                    modificarLabelMesaSeleccionada();
                }

            });
                
            }
            
            indice++;
        }
           
        System.out.println("salio del for");
        mesasList=md.listarMesas();
      mesasAgregadas=mesasList.size();
        
        actualizarComboBoxMesas();
        jDialog1.dispose();
    }//GEN-LAST:event_JbAceptarMesaActionPerformed

    private void cantidadMesasComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadMesasComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadMesasComboBoxActionPerformed

    private void JCEstadoDeMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCEstadoDeMesaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCEstadoDeMesaActionPerformed

    private void JbAceptarModificarMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbAceptarModificarMesaActionPerformed
        // Obtener el estado seleccionado del JComboBox
        String estadoSeleccionado = (String) JCEstadoDeMesa.getSelectedItem(); // JCEstadoDeMesa es tu JComboBox

        // Obtener la nueva capacidad de la mesa desde el JTextField
        String capacidadTexto = JtModificarCapMesas.getText(); // JtModificarCapMesas es tu JTextField para capacidad
   
        // Verificar que la capacidad sea un número válido
        int nuevaCapacidad = 0;
        try {
            nuevaCapacidad = Integer.parseInt(capacidadTexto);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, ingresa una capacidad válida.");
            return;
        }

        actualizarImagenMesa(selectedLabel, estadoSeleccionado);

        Mesa mesaSeleccionada = (Mesa) selectedLabel.getClientProperty("mesa");
        if (mesaSeleccionada != null) {
            mesaSeleccionada.setCapacidad(nuevaCapacidad);
            mesaSeleccionada.setEstado(estadoSeleccionado); 
            md.modificarMesa(mesaSeleccionada);
        }
        
      
        jDialog2.dispose();

        JOptionPane.showMessageDialog(this, "La mesa se modificó con éxito.");
    }//GEN-LAST:event_JbAceptarModificarMesaActionPerformed

    private void JbCancelarModificarMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbCancelarModificarMesaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JbCancelarModificarMesaActionPerformed

    private void JtModificarCapMesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtModificarCapMesasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtModificarCapMesasActionPerformed

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed

        ViewProducto vp = new ViewProducto();  
        vp.setSize(1000, 650);       
        escritorio.setLayout(null);
        escritorio.add(vp);  
        vp.setVisible(true);  
        vp.moveToFront();     

    }//GEN-LAST:event_btnProductosActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
          
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnProductos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductos2ActionPerformed
        
    }//GEN-LAST:event_btnProductos2ActionPerformed

    private void modificarLabelMesaSeleccionada(){
        Mesa mesaSeleccionada = (Mesa) selectedLabel.getClientProperty("mesa");

        if (mesaSeleccionada != null) {
            int numeroMesa = mesaSeleccionada.getIdMesa();
            int capacidad = mesaSeleccionada.getCapacidad(); 
            String estado = mesaSeleccionada.getEstado();    

            
            JlblNumMesa.setText("Número de Mesa: " + numeroMesa);
            JlblCapMesa.setText("Capacidad: " + capacidad);        
            JlblEstadoMesa.setText("Estado: " + estado);
            }else {
                JlblNumMesa.setText("No se ha seleccionado aun");
                JlblCapMesa.setText("No se ha seleccionado aun");        
                JlblEstadoMesa.setText("No se ha seleccionado aun");
            }
        }
    private void inicializarMesas() {
       mesaLabels[0] = JlblMesa1;
       mesaLabels[1] = JlblMesa2;
       mesaLabels[2] = JlblMesa3;
       mesaLabels[3] = JlblMesa4;
       mesaLabels[4] = JlblMesa5;
       mesaLabels[5] = JlblMesa6;
       mesaLabels[6] = JlblMesa7;
       mesaLabels[7] = JlblMesa8;
       mesaLabels[8] = JlblMesa9;
       mesaLabels[9] = JlblMesa10;
       mesaLabels[10] = JlblMesa11;
       mesaLabels[11] = JlblMesa12;
    }
    
    private void traerMesasDB(){
            int i=0;
        for (Mesa m:mesasList) {
            URL imageURL= getClass().getResource("/img/"+m.getEstado().toLowerCase()+".png");
          ImageIcon icono = new ImageIcon(imageURL);
             JLabel mesaLabel = mesaLabels[i];
                mesaLabel.setIcon(icono);
                mesaLabel.putClientProperty("mesa", m);
                mesaLabel.setCursor(new Cursor(Cursor.HAND_CURSOR));
                i++;
                
                    mesaLabel.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseEntered(MouseEvent e) {
                    // Cambiar el cursor cuando se pasa sobre el JLabel
                    mesaLabel.setCursor(new Cursor(Cursor.HAND_CURSOR));
                }

                @Override
                public void mouseClicked(MouseEvent e) {
                    if (selectedLabel != null) {
                        selectedLabel.setBorder(null);
                    }

                    mesaLabel.setBorder(BorderFactory.createLineBorder(Color.GREEN, 2));

                    selectedLabel = mesaLabel;
                    modificarLabelMesaSeleccionada();
                }

            });
                
        }
       
    
    
    }
    
    //da el numero de mesas que aun se pueden agregar
    private void actualizarComboBoxMesas() {
        
        int maxMesas = 12;

        cantidadMesasComboBox.removeAllItems();

        for (int i = 1; i <= maxMesas - mesasAgregadas; i++) {
            cantidadMesasComboBox.addItem(i + " Mesas");
        }
    }

//    private int contarMesas() {
//        int contador = 0;
//        for (JLabel mesaLabel : mesaLabels) {
//            if (mesaLabel.getClientProperty("mesa") != null) {
//                contador++;
//            }
//        }
//        return contador;
//    }
    
    private void actualizarImagenMesa(JLabel mesaLabel, String estado) {
        URL imageURL;
        ImageIcon icono;

        switch (estado.toLowerCase()) {
            case "libre":
                imageURL = getClass().getResource("/img/libre.png");
                break;
            case "ocupada":
                imageURL = getClass().getResource("/img/ocupada.png");
                break;
            case "atendida":
                imageURL = getClass().getResource("/img/atendida.png");
                break;
            case "reservada":
                imageURL = getClass().getResource("/img/reservada.png");
                break;
            default:
                System.out.println("Estado no reconocido: " + estado);
                return;
        }

        if (imageURL == null) {
            System.out.println("Error: La imagen para el estado " + estado + " no se encontró.");
            return;
        }

        icono = new ImageIcon(imageURL);
        mesaLabel.setIcon(icono);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JCEstadoDeMesa;
    private javax.swing.JButton JbAEliminarMesa;
    private javax.swing.JButton JbAceptarMesa;
    private javax.swing.JButton JbAceptarModificarMesa;
    private javax.swing.JButton JbAñadirMesa;
    private javax.swing.JButton JbCancelarModificarMesa;
    private javax.swing.JButton JbModificarMesa;
    private javax.swing.JLabel JlblCapMesa;
    private javax.swing.JLabel JlblEstadoMesa;
    private javax.swing.JLabel JlblMesa1;
    private javax.swing.JLabel JlblMesa10;
    private javax.swing.JLabel JlblMesa11;
    private javax.swing.JLabel JlblMesa12;
    private javax.swing.JLabel JlblMesa2;
    private javax.swing.JLabel JlblMesa3;
    private javax.swing.JLabel JlblMesa4;
    private javax.swing.JLabel JlblMesa5;
    private javax.swing.JLabel JlblMesa6;
    private javax.swing.JLabel JlblMesa7;
    private javax.swing.JLabel JlblMesa8;
    private javax.swing.JLabel JlblMesa9;
    private javax.swing.JLabel JlblMesaSeleccionada;
    private javax.swing.JLabel JlblNumMesa;
    private javax.swing.JTextField JtCapacidadMesas;
    private javax.swing.JTextField JtModificarCapMesas;
    private javax.swing.JButton btnProductos;
    private javax.swing.JButton btnProductos1;
    private javax.swing.JButton btnProductos2;
    private javax.swing.JComboBox<String> cantidadMesasComboBox;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JButton jButton3;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
