/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Image;
import java.beans.PropertyVetoException;
import javax.swing.ImageIcon;
import javax.swing.JInternalFrame;
import javax.swing.JPanel;
import AppPackage.AnimationClass;
/**
 *
 * @author ariel
 */
public class ViewLogin extends javax.swing.JFrame {
        
    /**
     * Creates new form ViewPrincipal
     */
    public ViewLogin() {
        
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        JlbRegistrarse = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jPfondo = new FondoPanel();
        JTRegistroNombre = new javax.swing.JTextField();
        JlblNewCamarero = new javax.swing.JLabel();
        JlblRegistroNombre = new javax.swing.JLabel();
        JlblRegistroDni = new javax.swing.JLabel();
        JTRegistroDni = new javax.swing.JTextField();
        JbRegistro1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Prueba = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setResizable(false);

        escritorio.setBackground(new java.awt.Color(102, 51, 0));
        escritorio.setForeground(new java.awt.Color(102, 51, 0));

        jPanel1.setBackground(new java.awt.Color(51, 0, 0));
        jPanel1.setForeground(new java.awt.Color(102, 51, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(219, 198, 83));
        jLabel3.setText("RESTAURANTE");
        jLabel3.setToolTipText("");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, 330, 51));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/olla-calienteiCON.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 90, 70));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, 100));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 40, 580));

        JlbRegistrarse.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        JlbRegistrarse.setForeground(new java.awt.Color(219, 198, 83));
        JlbRegistrarse.setText("Registrarse en el sistema");
        JlbRegistrarse.setToolTipText("");
        JlbRegistrarse.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JlbRegistrarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JlbRegistrarseMouseClicked(evt);
            }
        });
        jPanel1.add(JlbRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 590, 270, 40));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/camarero.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 90, 70));

        jLabel6.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(219, 198, 83));
        jLabel6.setText("Usuario:");
        jLabel6.setToolTipText("");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 90, 40));

        jSeparator2.setBackground(new java.awt.Color(219, 198, 83));
        jSeparator2.setForeground(new java.awt.Color(219, 198, 83));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 280, 20));

        jSeparator3.setBackground(new java.awt.Color(219, 198, 83));
        jSeparator3.setForeground(new java.awt.Color(219, 198, 83));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 280, 20));

        jTextField1.setBackground(new java.awt.Color(51, 0, 0));
        jTextField1.setForeground(new java.awt.Color(204, 204, 204));
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 324, 280, 40));

        jPasswordField1.setBackground(new java.awt.Color(51, 0, 0));
        jPasswordField1.setForeground(new java.awt.Color(204, 204, 204));
        jPasswordField1.setText("jPasswordField1");
        jPasswordField1.setBorder(null);
        jPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 432, 280, 30));

        jButton1.setBackground(new java.awt.Color(51, 0, 0));
        jButton1.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(219, 198, 83));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Offline.png"))); // NOI18N
        jButton1.setText("  Ingresar");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Online.png"))); // NOI18N
        jButton1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Online.png"))); // NOI18N
        jButton1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Online.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 210, 70));

        jPfondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPfondo.add(JTRegistroNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 370, 40));

        JlblNewCamarero.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        JlblNewCamarero.setForeground(new java.awt.Color(219, 198, 83));
        JlblNewCamarero.setText("Nuevo Camarero:");
        JlblNewCamarero.setToolTipText("");
        JlblNewCamarero.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPfondo.add(JlblNewCamarero, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 300, 60));

        JlblRegistroNombre.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        JlblRegistroNombre.setForeground(new java.awt.Color(219, 198, 83));
        JlblRegistroNombre.setText("Nombre:");
        JlblRegistroNombre.setToolTipText("");
        JlblRegistroNombre.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPfondo.add(JlblRegistroNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 300, 60));

        JlblRegistroDni.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        JlblRegistroDni.setForeground(new java.awt.Color(219, 198, 83));
        JlblRegistroDni.setText("DNI:");
        JlblRegistroDni.setToolTipText("");
        JlblRegistroDni.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPfondo.add(JlblRegistroDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 300, 60));
        jPfondo.add(JTRegistroDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 370, 40));

        JbRegistro1.setText("Registrarme!");
        jPfondo.add(JbRegistro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, -1, -1));

        jPanel1.add(jPfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 910, 580));

        jLabel8.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(219, 198, 83));
        jLabel8.setText("Registro de camareros");
        jLabel8.setToolTipText("");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 300, 90));

        jLabel9.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(219, 198, 83));
        jLabel9.setText("Contraseña:");
        jLabel9.setToolTipText("");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 130, 40));

        Prueba.setText("Prueba");
        Prueba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PruebaActionPerformed(evt);
            }
        });
        jPanel1.add(Prueba, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 510, -1, -1));

        escritorio.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void JlbRegistrarseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JlbRegistrarseMouseClicked
        JlbRegistrarse.setText("Registrarse en el sistema");
        Color amarillito = new Color(219, 198, 83);
        JlbRegistrarse.setForeground(amarillito);
        AnimationClass registro = new AnimationClass();
        registro.jLabelYUp(-150, 30, 10, 5,JlblNewCamarero );
        registro.jLabelYUp(-150, 200, 10, 5,JlblRegistroDni );
        registro.jLabelYUp(-150, 80, 10, 5,JlblRegistroNombre );
        registro.jButtonYUp(-150, 350, 10, 5, Prueba);
        registro.jTextFieldYUp(-150, 250, 10, 5, JTRegistroDni);
        registro.jTextFieldYUp(-150, 130, 10, 5, JTRegistroNombre);
    }//GEN-LAST:event_JlbRegistrarseMouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void PruebaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PruebaActionPerformed
        ViewMenuPrincipal vmp = new ViewMenuPrincipal();
        vmp.setVisible(true);
        vmp.setSize(1318,779);
        escritorio.add(vmp);
        vmp.moveToFront();
    }//GEN-LAST:event_PruebaActionPerformed

    
  
    private void agregarInternalFrame(JInternalFrame ifr) {
        escritorio.removeAll();
        escritorio.repaint();
        
        try {
            ifr.setMaximum(true);
        } catch (PropertyVetoException e) {
            e.printStackTrace();
        }
        
        ifr.setVisible(true);
        escritorio.add(ifr);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTRegistroDni;
    private javax.swing.JTextField JTRegistroNombre;
    private javax.swing.JButton JbRegistro1;
    private javax.swing.JLabel JlbRegistrarse;
    private javax.swing.JLabel JlblNewCamarero;
    private javax.swing.JLabel JlblRegistroDni;
    private javax.swing.JLabel JlblRegistroNombre;
    private javax.swing.JButton Prueba;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPanel jPfondo;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
class FondoPanel extends JPanel {
        private Image imagen;
        
        @Override
        public void paint(Graphics g){
            imagen = new ImageIcon(getClass().getResource("/img/un_restaurante[1].png")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(),this);
            
            setOpaque(false);
            super.paint(g);
        }
    }
}
