/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import Entidades.Conexion;
import Entidades.Pedido;
import Persistencia.PedidoData;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.time.LocalDateTime;
import java.util.ArrayList;
import javax.swing.JOptionPane;
/**
 *
 * @author USUARIO
 */
public class ViewPedido extends javax.swing.JInternalFrame {

    /**
     * Creates new form ViewPedido
     */
    public ViewPedido() {
        initComponents();
        mostrarPedidosEnTabla();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogTicket = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonImprimir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        pagado = new javax.swing.JButton();
        jButtonEntregar = new javax.swing.JButton();
        jButtonAnulado = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtpedidos = new javax.swing.JTable();
        jButtonTicket = new javax.swing.JButton();

        jPanel3.setBackground(new java.awt.Color(68, 4, 4));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/factura.png"))); // NOI18N
        jLabel2.setText("TICKET");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 260, 80));

        jTable1.setBackground(new java.awt.Color(133, 23, 23));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Ticket", "Detalle", "Mesa n°", "Fecha y Hora", "Monto Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 870, 150));

        jButtonImprimir.setBackground(new java.awt.Color(163, 45, 45));
        jButtonImprimir.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jButtonImprimir.setForeground(new java.awt.Color(255, 255, 255));
        jButtonImprimir.setText("Imprimir Ticket");
        jButtonImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImprimirActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 270, 210, 40));

        javax.swing.GroupLayout jDialogTicketLayout = new javax.swing.GroupLayout(jDialogTicket.getContentPane());
        jDialogTicket.getContentPane().setLayout(jDialogTicketLayout);
        jDialogTicketLayout.setHorizontalGroup(
            jDialogTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogTicketLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 933, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDialogTicketLayout.setVerticalGroup(
            jDialogTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogTicketLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(51, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(238, 238, 93));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pedido-en-linea.png"))); // NOI18N
        jLabel1.setText("PEDIDOS");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, -1, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 0, 0));
        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(773, 9, 43, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 15, 825, -1));

        pagado.setBackground(new java.awt.Color(102, 0, 0));
        pagado.setFont(new java.awt.Font("Cambria", 1, 15)); // NOI18N
        pagado.setForeground(new java.awt.Color(255, 204, 153));
        pagado.setText("Pago/inpago");
        pagado.setIconTextGap(12);
        pagado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagadojBtnBuscar(evt);
            }
        });
        jPanel1.add(pagado, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 540, 137, 40));

        jButtonEntregar.setBackground(new java.awt.Color(102, 0, 0));
        jButtonEntregar.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        jButtonEntregar.setForeground(new java.awt.Color(255, 204, 153));
        jButtonEntregar.setText("Cambiar estado");
        jButtonEntregar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonEntregar.setIconTextGap(12);
        jButtonEntregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEntregarjBtnBuscar(evt);
            }
        });
        jPanel1.add(jButtonEntregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 150, 40));

        jButtonAnulado.setBackground(new java.awt.Color(102, 0, 0));
        jButtonAnulado.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jButtonAnulado.setForeground(new java.awt.Color(255, 204, 153));
        jButtonAnulado.setText("Anulado");
        jButtonAnulado.setIconTextGap(12);
        jButtonAnulado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnuladojBtnBuscar(evt);
            }
        });
        jPanel1.add(jButtonAnulado, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 540, 137, 40));

        jtpedidos.setBackground(new java.awt.Color(102, 0, 0));
        jtpedidos.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jtpedidos.setForeground(new java.awt.Color(255, 255, 255));
        jtpedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Pedido", "Mesa n°", "Moso n°", "Cliente n°", "Fecha y hora", "Estado", "Abonado", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtpedidos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 115, 830, 417));

        jButtonTicket.setBackground(new java.awt.Color(102, 0, 0));
        jButtonTicket.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jButtonTicket.setForeground(new java.awt.Color(255, 204, 153));
        jButtonTicket.setText("Ticket");
        jButtonTicket.setIconTextGap(12);
        jButtonTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTicketjBtnBuscar(evt);
            }
        });
        jPanel1.add(jButtonTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 540, 137, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 853, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void pagadojBtnBuscar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagadojBtnBuscar
        int selectedRow = jtpedidos.getSelectedRow();
        if (selectedRow != -1) {
            int idPedido = (int) jtpedidos.getValueAt(selectedRow, 0); // ID en la primera columna
            String estadoActual = (String) jtpedidos.getValueAt(selectedRow, 6); // Columna de pago
            boolean nuevoEstadoPago = estadoActual.equals("No Pagado");

            PedidoData pedidoData = new PedidoData();
            pedidoData.cambiarEstadoPago(idPedido, nuevoEstadoPago);

            // Actualizar en la tabla visualmente
            jtpedidos.setValueAt(nuevoEstadoPago ? "Pagado" : "No Pagado", selectedRow, 6);
            JOptionPane.showMessageDialog(this, "Estado de pago actualizado.");
        } else {
            JOptionPane.showMessageDialog(this, "Selecciona un pedido para cambiar su estado de pago.");
        }
    }//GEN-LAST:event_pagadojBtnBuscar

    private void jButtonEntregarjBtnBuscar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEntregarjBtnBuscar
        int selectedRow = jtpedidos.getSelectedRow();
        if (selectedRow != -1) {
            int idPedido = (int) jtpedidos.getValueAt(selectedRow, 0); // ID en la primera columna
            String estadoActual = (String) jtpedidos.getValueAt(selectedRow, 5); // Columna de entrega
            boolean nuevoEstadoEntrega = estadoActual.equals("No Entregado");

            PedidoData pedidoData = new PedidoData();
            pedidoData.cambiarEstadoEntrega(idPedido, nuevoEstadoEntrega);

            // Actualizar en la tabla visualmente
            jtpedidos.setValueAt(nuevoEstadoEntrega ? "Entregado" : "No Entregado", selectedRow, 5);
            JOptionPane.showMessageDialog(this, "Estado de entrega actualizado.");
        } else {
            JOptionPane.showMessageDialog(this, "Selecciona un pedido para cambiar su estado de entrega.");
        }
    }//GEN-LAST:event_jButtonEntregarjBtnBuscar

    private void jButtonAnuladojBtnBuscar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnuladojBtnBuscar
        int selectedRow = jtpedidos.getSelectedRow();
        if (selectedRow != -1) {
            int idPedido = (int) jtpedidos.getValueAt(selectedRow, 0); // Asumiendo que el ID está en la primera columna
            PedidoData pedidoData = new PedidoData();
            pedidoData.borrarPedido(idPedido);

            // Remover visualmente la fila de la tabla
            ((DefaultTableModel) jtpedidos.getModel()).removeRow(selectedRow);
            JOptionPane.showMessageDialog(this, "Pedido eliminado.");
        } else {
            JOptionPane.showMessageDialog(this, "Selecciona un pedido para eliminar.");
        }
    }//GEN-LAST:event_jButtonAnuladojBtnBuscar

    private void jButtonTicketjBtnBuscar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTicketjBtnBuscar
    int filaSeleccionada = jtpedidos.getSelectedRow(); // Obtén la fila seleccionada de jtpedidos
    
    if (filaSeleccionada != -1) { // Verifica si se seleccionó una fila
        int idPedido = (int) jtpedidos.getValueAt(filaSeleccionada, 0); // Obtén el ID del pedido
        mostrarTablaTicket(idPedido); // Llama al método para mostrar los detalles del pedido
        jDialogTicket.pack();
        jDialogTicket.setLocationRelativeTo(this);
        jDialogTicket.setVisible(true);
    } else {
        JOptionPane.showMessageDialog(this, "Por favor, selecciona un pedido para mostrar su ticket.");
    }
    }//GEN-LAST:event_jButtonTicketjBtnBuscar

    private void jButtonImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImprimirActionPerformed
       JOptionPane.showMessageDialog(this, "Imprimiendo su ticket pipipi *ruido de impresora* ");
    }//GEN-LAST:event_jButtonImprimirActionPerformed

    //metodos para agregar el pedido a tabla
    public void agregarPedidoATabla(int idPedido, int idCliente, int idMesa, int idMesero, double montoTotal, String fechaPedido, String estado, String pagado) {
    DefaultTableModel modelo = (DefaultTableModel) jtpedidos.getModel();
    Object[] fila = {idPedido, idCliente, idMesa, idMesero, montoTotal, fechaPedido, estado, pagado};
    modelo.addRow(fila);
}
    
    
    private void mostrarPedidosEnTabla() {
    PedidoData pedidoData = new PedidoData();
    List<Pedido> pedidos = pedidoData.obtenerTodosLosPedidos();

    DefaultTableModel modelo = (DefaultTableModel) jtpedidos.getModel();
    modelo.setRowCount(0); // Limpiar la tabla antes de agregar datos

    for (Pedido pedido : pedidos) {
        Object[] fila = {
            pedido.getIdPedido(),
            pedido.getMesa().getIdMesa(),
            pedido.getMesero().getId(),
            pedido.getCliente().getId(),
            pedido.getFecha().toString(),
            pedido.isEntregado() ? "Entregado" : "No entregado",
            pedido.isPagado() ? "No Pagado" : "Pagado",
            pedido.getMontoTotal()
        };
        modelo.addRow(fila);
    }
}
private void mostrarTablaTicket(int idPedido) {
    PedidoData pedidoData = new PedidoData();
    Pedido pedido = pedidoData.obtenerPedidoPorId(idPedido); 

    if (pedido != null) {
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setRowCount(0); 

        String detalle = pedidoData.detalleConcatenado(pedido.getIdPedido());
        Object[] fila = {
            pedido.getIdPedido(),
            detalle,
            pedido.getMesa().getIdMesa(),
            pedido.getFecha().toString(),
            pedido.getMontoTotal()
        };
        modelo.addRow(fila);  
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAnulado;
    private javax.swing.JButton jButtonEntregar;
    private javax.swing.JButton jButtonImprimir;
    private javax.swing.JButton jButtonTicket;
    private javax.swing.JDialog jDialogTicket;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jtpedidos;
    private javax.swing.JButton pagado;
    // End of variables declaration//GEN-END:variables
}
